package br.com.adem.iconv;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import br.com.adem.iconv.model.Municipio;

/**
 * Created by eduardo on 11/04/2016.
 */
public class MunicipioAuxiliar4 {

    public static List<Municipio> listar() {
        List<Municipio> lista = new ArrayList<Municipio>();

        lista.add(new Municipio(new Integer("00034"),"Aceguá", new Integer("43")));
        lista.add(new Municipio(new Integer("00059"),"Água Santa", new Integer("43")));
        lista.add(new Municipio(new Integer("00109"),"Agudo", new Integer("43")));
        lista.add(new Municipio(new Integer("00208"),"Ajuricaba", new Integer("43")));
        lista.add(new Municipio(new Integer("00307"),"Alecrim", new Integer("43")));
        lista.add(new Municipio(new Integer("00406"),"Alegrete", new Integer("43")));
        lista.add(new Municipio(new Integer("00455"),"Alegria", new Integer("43")));
        lista.add(new Municipio(new Integer("00471"),"Almirante Tamandaré do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("00505"),"Alpestre", new Integer("43")));
        lista.add(new Municipio(new Integer("00554"),"Alto Alegre", new Integer("43")));
        lista.add(new Municipio(new Integer("00570"),"Alto Feliz", new Integer("43")));
        lista.add(new Municipio(new Integer("00604"),"Alvorada", new Integer("43")));
        lista.add(new Municipio(new Integer("00638"),"Amaral Ferrador", new Integer("43")));
        lista.add(new Municipio(new Integer("00646"),"Ametista do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("00661"),"André da Rocha", new Integer("43")));
        lista.add(new Municipio(new Integer("00703"),"Anta Gorda", new Integer("43")));
        lista.add(new Municipio(new Integer("00802"),"Antônio Prado", new Integer("43")));
        lista.add(new Municipio(new Integer("00851"),"Arambaré", new Integer("43")));
        lista.add(new Municipio(new Integer("00877"),"Araricá", new Integer("43")));
        lista.add(new Municipio(new Integer("00901"),"Aratiba", new Integer("43")));
        lista.add(new Municipio(new Integer("01008"),"Arroio do Meio", new Integer("43")));
        lista.add(new Municipio(new Integer("01057"),"Arroio do Sal", new Integer("43")));
        lista.add(new Municipio(new Integer("01073"),"Arroio do Padre", new Integer("43")));
        lista.add(new Municipio(new Integer("01107"),"Arroio dos Ratos", new Integer("43")));
        lista.add(new Municipio(new Integer("01206"),"Arroio do Tigre", new Integer("43")));
        lista.add(new Municipio(new Integer("01305"),"Arroio Grande", new Integer("43")));
        lista.add(new Municipio(new Integer("01404"),"Arvorezinha", new Integer("43")));
        lista.add(new Municipio(new Integer("01503"),"Augusto Pestana", new Integer("43")));
        lista.add(new Municipio(new Integer("01552"),"Áurea", new Integer("43")));
        lista.add(new Municipio(new Integer("01602"),"Bagé", new Integer("43")));
        lista.add(new Municipio(new Integer("01636"),"Balneário Pinhal", new Integer("43")));
        lista.add(new Municipio(new Integer("01651"),"Barão", new Integer("43")));
        lista.add(new Municipio(new Integer("01701"),"Barão de Cotegipe", new Integer("43")));
        lista.add(new Municipio(new Integer("01750"),"Barão do Triunfo", new Integer("43")));
        lista.add(new Municipio(new Integer("01800"),"Barracão", new Integer("43")));
        lista.add(new Municipio(new Integer("01859"),"Barra do Guarita", new Integer("43")));
        lista.add(new Municipio(new Integer("01875"),"Barra do Quaraí", new Integer("43")));
        lista.add(new Municipio(new Integer("01909"),"Barra do Ribeiro", new Integer("43")));
        lista.add(new Municipio(new Integer("01925"),"Barra do Rio Azul", new Integer("43")));
        lista.add(new Municipio(new Integer("01958"),"Barra Funda", new Integer("43")));
        lista.add(new Municipio(new Integer("02006"),"Barros Cassal", new Integer("43")));
        lista.add(new Municipio(new Integer("02055"),"Benjamin Constant do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("02105"),"Bento Gonçalves", new Integer("43")));
        lista.add(new Municipio(new Integer("02154"),"Boa Vista das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("02204"),"Boa Vista do Buricá", new Integer("43")));
        lista.add(new Municipio(new Integer("02220"),"Boa Vista do Cadeado", new Integer("43")));
        lista.add(new Municipio(new Integer("02238"),"Boa Vista do Incra", new Integer("43")));
        lista.add(new Municipio(new Integer("02253"),"Boa Vista do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("02303"),"Bom Jesus", new Integer("43")));
        lista.add(new Municipio(new Integer("02352"),"Bom Princípio", new Integer("43")));
        lista.add(new Municipio(new Integer("02378"),"Bom Progresso", new Integer("43")));
        lista.add(new Municipio(new Integer("02402"),"Bom Retiro do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("02451"),"Boqueirão do Leão", new Integer("43")));
        lista.add(new Municipio(new Integer("02501"),"Bossoroca", new Integer("43")));
        lista.add(new Municipio(new Integer("02584"),"Bozano", new Integer("43")));
        lista.add(new Municipio(new Integer("02600"),"Braga", new Integer("43")));
        lista.add(new Municipio(new Integer("02659"),"Brochier", new Integer("43")));
        lista.add(new Municipio(new Integer("02709"),"Butiá", new Integer("43")));
        lista.add(new Municipio(new Integer("02808"),"Caçapava do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("02907"),"Cacequi", new Integer("43")));
        lista.add(new Municipio(new Integer("03004"),"Cachoeira do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("03103"),"Cachoeirinha", new Integer("43")));
        lista.add(new Municipio(new Integer("03202"),"Cacique Doble", new Integer("43")));
        lista.add(new Municipio(new Integer("03301"),"Caibaté", new Integer("43")));
        lista.add(new Municipio(new Integer("03400"),"Caiçara", new Integer("43")));
        lista.add(new Municipio(new Integer("03509"),"Camaquã", new Integer("43")));
        lista.add(new Municipio(new Integer("03558"),"Camargo", new Integer("43")));
        lista.add(new Municipio(new Integer("03608"),"Cambará do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("03673"),"Campestre da Serra", new Integer("43")));
        lista.add(new Municipio(new Integer("03707"),"Campina das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("03806"),"Campinas do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("03905"),"Campo Bom", new Integer("43")));
        lista.add(new Municipio(new Integer("04002"),"Campo Novo", new Integer("43")));
        lista.add(new Municipio(new Integer("04101"),"Campos Borges", new Integer("43")));
        lista.add(new Municipio(new Integer("04200"),"Candelária", new Integer("43")));
        lista.add(new Municipio(new Integer("04309"),"Cândido Godói", new Integer("43")));
        lista.add(new Municipio(new Integer("04358"),"Candiota", new Integer("43")));
        lista.add(new Municipio(new Integer("04408"),"Canela", new Integer("43")));
        lista.add(new Municipio(new Integer("04507"),"Canguçu", new Integer("43")));
        lista.add(new Municipio(new Integer("04606"),"Canoas", new Integer("43")));
        lista.add(new Municipio(new Integer("04614"),"Canudos do Vale", new Integer("43")));
        lista.add(new Municipio(new Integer("04622"),"Capão Bonito do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("04630"),"Capão da Canoa", new Integer("43")));
        lista.add(new Municipio(new Integer("04655"),"Capão do Cipó", new Integer("43")));
        lista.add(new Municipio(new Integer("04663"),"Capão do Leão", new Integer("43")));
        lista.add(new Municipio(new Integer("04671"),"Capivari do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("04689"),"Capela de Santana", new Integer("43")));
        lista.add(new Municipio(new Integer("04697"),"Capitão", new Integer("43")));
        lista.add(new Municipio(new Integer("04705"),"Carazinho", new Integer("43")));
        lista.add(new Municipio(new Integer("04713"),"Caraá", new Integer("43")));
        lista.add(new Municipio(new Integer("04804"),"Carlos Barbosa", new Integer("43")));
        lista.add(new Municipio(new Integer("04853"),"Carlos Gomes", new Integer("43")));
        lista.add(new Municipio(new Integer("04903"),"Casca", new Integer("43")));
        lista.add(new Municipio(new Integer("04952"),"Caseiros", new Integer("43")));
        lista.add(new Municipio(new Integer("05009"),"Catuípe", new Integer("43")));
        lista.add(new Municipio(new Integer("05108"),"Caxias do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("05116"),"Centenário", new Integer("43")));
        lista.add(new Municipio(new Integer("05124"),"Cerrito", new Integer("43")));
        lista.add(new Municipio(new Integer("05132"),"Cerro Branco", new Integer("43")));
        lista.add(new Municipio(new Integer("05157"),"Cerro Grande", new Integer("43")));
        lista.add(new Municipio(new Integer("05173"),"Cerro Grande do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("05207"),"Cerro Largo", new Integer("43")));
        lista.add(new Municipio(new Integer("05306"),"Chapada", new Integer("43")));
        lista.add(new Municipio(new Integer("05355"),"Charqueadas", new Integer("43")));
        lista.add(new Municipio(new Integer("05371"),"Charrua", new Integer("43")));
        lista.add(new Municipio(new Integer("05405"),"Chiapetta", new Integer("43")));
        lista.add(new Municipio(new Integer("05439"),"Chuí", new Integer("43")));
        lista.add(new Municipio(new Integer("05447"),"Chuvisca", new Integer("43")));
        lista.add(new Municipio(new Integer("05454"),"Cidreira", new Integer("43")));
        lista.add(new Municipio(new Integer("05504"),"Ciríaco", new Integer("43")));
        lista.add(new Municipio(new Integer("05587"),"Colinas", new Integer("43")));
        lista.add(new Municipio(new Integer("05603"),"Colorado", new Integer("43")));
        lista.add(new Municipio(new Integer("05702"),"Condor", new Integer("43")));
        lista.add(new Municipio(new Integer("05801"),"Constantina", new Integer("43")));
        lista.add(new Municipio(new Integer("05835"),"Coqueiro Baixo", new Integer("43")));
        lista.add(new Municipio(new Integer("05850"),"Coqueiros do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("05871"),"Coronel Barros", new Integer("43")));
        lista.add(new Municipio(new Integer("05900"),"Coronel Bicaco", new Integer("43")));
        lista.add(new Municipio(new Integer("05934"),"Coronel Pilar", new Integer("43")));
        lista.add(new Municipio(new Integer("05959"),"Cotiporã", new Integer("43")));
        lista.add(new Municipio(new Integer("05975"),"Coxilha", new Integer("43")));
        lista.add(new Municipio(new Integer("06007"),"Crissiumal", new Integer("43")));
        lista.add(new Municipio(new Integer("06056"),"Cristal", new Integer("43")));
        lista.add(new Municipio(new Integer("06072"),"Cristal do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("06106"),"Cruz Alta", new Integer("43")));
        lista.add(new Municipio(new Integer("06130"),"Cruzaltense", new Integer("43")));
        lista.add(new Municipio(new Integer("06205"),"Cruzeiro do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("06304"),"David Canabarro", new Integer("43")));
        lista.add(new Municipio(new Integer("06320"),"Derrubadas", new Integer("43")));
        lista.add(new Municipio(new Integer("06353"),"Dezesseis de Novembro", new Integer("43")));
        lista.add(new Municipio(new Integer("06379"),"Dilermando de Aguiar", new Integer("43")));
        lista.add(new Municipio(new Integer("06403"),"Dois Irmãos", new Integer("43")));
        lista.add(new Municipio(new Integer("06429"),"Dois Irmãos das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("06452"),"Dois Lajeados", new Integer("43")));
        lista.add(new Municipio(new Integer("06502"),"Dom Feliciano", new Integer("43")));
        lista.add(new Municipio(new Integer("06551"),"Dom Pedro de Alcântara", new Integer("43")));
        lista.add(new Municipio(new Integer("06601"),"Dom Pedrito", new Integer("43")));
        lista.add(new Municipio(new Integer("06700"),"Dona Francisca", new Integer("43")));
        lista.add(new Municipio(new Integer("06734"),"Doutor Maurício Cardoso", new Integer("43")));
        lista.add(new Municipio(new Integer("06759"),"Doutor Ricardo", new Integer("43")));
        lista.add(new Municipio(new Integer("06767"),"Eldorado do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("06809"),"Encantado", new Integer("43")));
        lista.add(new Municipio(new Integer("06908"),"Encruzilhada do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("06924"),"Engenho Velho", new Integer("43")));
        lista.add(new Municipio(new Integer("06932"),"Entre-Ijuís", new Integer("43")));
        lista.add(new Municipio(new Integer("06957"),"Entre Rios do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("06973"),"Erebango", new Integer("43")));
        lista.add(new Municipio(new Integer("07005"),"Erechim", new Integer("43")));
        lista.add(new Municipio(new Integer("07054"),"Ernestina", new Integer("43")));
        lista.add(new Municipio(new Integer("07104"),"Herval", new Integer("43")));
        lista.add(new Municipio(new Integer("07203"),"Erval Grande", new Integer("43")));
        lista.add(new Municipio(new Integer("07302"),"Erval Seco", new Integer("43")));
        lista.add(new Municipio(new Integer("07401"),"Esmeralda", new Integer("43")));
        lista.add(new Municipio(new Integer("07450"),"Esperança do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("07500"),"Espumoso", new Integer("43")));
        lista.add(new Municipio(new Integer("07559"),"Estação", new Integer("43")));
        lista.add(new Municipio(new Integer("07609"),"Estância Velha", new Integer("43")));
        lista.add(new Municipio(new Integer("07708"),"Esteio", new Integer("43")));
        lista.add(new Municipio(new Integer("07807"),"Estrela", new Integer("43")));
        lista.add(new Municipio(new Integer("07815"),"Estrela Velha", new Integer("43")));
        lista.add(new Municipio(new Integer("07831"),"Eugênio de Castro", new Integer("43")));
        lista.add(new Municipio(new Integer("07864"),"Fagundes Varela", new Integer("43")));
        lista.add(new Municipio(new Integer("07906"),"Farroupilha", new Integer("43")));
        lista.add(new Municipio(new Integer("08003"),"Faxinal do Soturno", new Integer("43")));
        lista.add(new Municipio(new Integer("08052"),"Faxinalzinho", new Integer("43")));
        lista.add(new Municipio(new Integer("08078"),"Fazenda Vilanova", new Integer("43")));
        lista.add(new Municipio(new Integer("08102"),"Feliz", new Integer("43")));
        lista.add(new Municipio(new Integer("08201"),"Flores da Cunha", new Integer("43")));
        lista.add(new Municipio(new Integer("08250"),"Floriano Peixoto", new Integer("43")));
        lista.add(new Municipio(new Integer("08300"),"Fontoura Xavier", new Integer("43")));
        lista.add(new Municipio(new Integer("08409"),"Formigueiro", new Integer("43")));
        lista.add(new Municipio(new Integer("08433"),"Forquetinha", new Integer("43")));
        lista.add(new Municipio(new Integer("08458"),"Fortaleza dos Valos", new Integer("43")));
        lista.add(new Municipio(new Integer("08508"),"Frederico Westphalen", new Integer("43")));
        lista.add(new Municipio(new Integer("08607"),"Garibaldi", new Integer("43")));
        lista.add(new Municipio(new Integer("08656"),"Garruchos", new Integer("43")));
        lista.add(new Municipio(new Integer("08706"),"Gaurama", new Integer("43")));
        lista.add(new Municipio(new Integer("08805"),"General Câmara", new Integer("43")));
        lista.add(new Municipio(new Integer("08854"),"Gentil", new Integer("43")));
        lista.add(new Municipio(new Integer("08904"),"Getúlio Vargas", new Integer("43")));
        lista.add(new Municipio(new Integer("09001"),"Giruá", new Integer("43")));
        lista.add(new Municipio(new Integer("09050"),"Glorinha", new Integer("43")));
        lista.add(new Municipio(new Integer("09100"),"Gramado", new Integer("43")));
        lista.add(new Municipio(new Integer("09126"),"Gramado dos Loureiros", new Integer("43")));
        lista.add(new Municipio(new Integer("09159"),"Gramado Xavier", new Integer("43")));
        lista.add(new Municipio(new Integer("09209"),"Gravataí", new Integer("43")));
        lista.add(new Municipio(new Integer("09258"),"Guabiju", new Integer("43")));
        lista.add(new Municipio(new Integer("09308"),"Guaíba", new Integer("43")));
        lista.add(new Municipio(new Integer("09407"),"Guaporé", new Integer("43")));
        lista.add(new Municipio(new Integer("09506"),"Guarani das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("09555"),"Harmonia", new Integer("43")));
        lista.add(new Municipio(new Integer("09571"),"Herveiras", new Integer("43")));
        lista.add(new Municipio(new Integer("09605"),"Horizontina", new Integer("43")));
        lista.add(new Municipio(new Integer("09654"),"Hulha Negra", new Integer("43")));
        lista.add(new Municipio(new Integer("09704"),"Humaitá", new Integer("43")));
        lista.add(new Municipio(new Integer("09753"),"Ibarama", new Integer("43")));
        lista.add(new Municipio(new Integer("09803"),"Ibiaçá", new Integer("43")));
        lista.add(new Municipio(new Integer("09902"),"Ibiraiaras", new Integer("43")));
        lista.add(new Municipio(new Integer("09951"),"Ibirapuitã", new Integer("43")));
        lista.add(new Municipio(new Integer("10009"),"Ibirubá", new Integer("43")));
        lista.add(new Municipio(new Integer("10108"),"Igrejinha", new Integer("43")));
        lista.add(new Municipio(new Integer("10207"),"Ijuí", new Integer("43")));
        lista.add(new Municipio(new Integer("10306"),"Ilópolis", new Integer("43")));
        lista.add(new Municipio(new Integer("10330"),"Imbé", new Integer("43")));
        lista.add(new Municipio(new Integer("10363"),"Imigrante", new Integer("43")));
        lista.add(new Municipio(new Integer("10405"),"Independência", new Integer("43")));
        lista.add(new Municipio(new Integer("10413"),"Inhacorá", new Integer("43")));
        lista.add(new Municipio(new Integer("10439"),"Ipê", new Integer("43")));
        lista.add(new Municipio(new Integer("10462"),"Ipiranga do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("10504"),"Iraí", new Integer("43")));
        lista.add(new Municipio(new Integer("10538"),"Itaara", new Integer("43")));
        lista.add(new Municipio(new Integer("10553"),"Itacurubi", new Integer("43")));
        lista.add(new Municipio(new Integer("10579"),"Itapuca", new Integer("43")));
        lista.add(new Municipio(new Integer("10603"),"Itaqui", new Integer("43")));
        lista.add(new Municipio(new Integer("10652"),"Itati", new Integer("43")));
        lista.add(new Municipio(new Integer("10702"),"Itatiba do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("10751"),"Ivorá", new Integer("43")));
        lista.add(new Municipio(new Integer("10801"),"Ivoti", new Integer("43")));
        lista.add(new Municipio(new Integer("10850"),"Jaboticaba", new Integer("43")));
        lista.add(new Municipio(new Integer("10876"),"Jacuizinho", new Integer("43")));
        lista.add(new Municipio(new Integer("10900"),"Jacutinga", new Integer("43")));
        lista.add(new Municipio(new Integer("11007"),"Jaguarão", new Integer("43")));
        lista.add(new Municipio(new Integer("11106"),"Jaguari", new Integer("43")));
        lista.add(new Municipio(new Integer("11122"),"Jaquirana", new Integer("43")));
        lista.add(new Municipio(new Integer("11130"),"Jari", new Integer("43")));
        lista.add(new Municipio(new Integer("11155"),"Jóia", new Integer("43")));
        lista.add(new Municipio(new Integer("11205"),"Júlio de Castilhos", new Integer("43")));
        lista.add(new Municipio(new Integer("11239"),"Lagoa Bonita do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("11254"),"Lagoão", new Integer("43")));
        lista.add(new Municipio(new Integer("11270"),"Lagoa dos Três Cantos", new Integer("43")));
        lista.add(new Municipio(new Integer("11304"),"Lagoa Vermelha", new Integer("43")));
        lista.add(new Municipio(new Integer("11403"),"Lajeado", new Integer("43")));
        lista.add(new Municipio(new Integer("11429"),"Lajeado do Bugre", new Integer("43")));
        lista.add(new Municipio(new Integer("11502"),"Lavras do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("11601"),"Liberato Salzano", new Integer("43")));
        lista.add(new Municipio(new Integer("11627"),"Lindolfo Collor", new Integer("43")));
        lista.add(new Municipio(new Integer("11643"),"Linha Nova", new Integer("43")));
        lista.add(new Municipio(new Integer("11700"),"Machadinho", new Integer("43")));
        lista.add(new Municipio(new Integer("11718"),"Maçambará", new Integer("43")));
        lista.add(new Municipio(new Integer("11734"),"Mampituba", new Integer("43")));
        lista.add(new Municipio(new Integer("11759"),"Manoel Viana", new Integer("43")));
        lista.add(new Municipio(new Integer("11775"),"Maquiné", new Integer("43")));
        lista.add(new Municipio(new Integer("11791"),"Maratá", new Integer("43")));
        lista.add(new Municipio(new Integer("11809"),"Marau", new Integer("43")));
        lista.add(new Municipio(new Integer("11908"),"Marcelino Ramos", new Integer("43")));
        lista.add(new Municipio(new Integer("11981"),"Mariana Pimentel", new Integer("43")));
        lista.add(new Municipio(new Integer("12005"),"Mariano Moro", new Integer("43")));
        lista.add(new Municipio(new Integer("12054"),"Marques de Souza", new Integer("43")));
        lista.add(new Municipio(new Integer("12104"),"Mata", new Integer("43")));
        lista.add(new Municipio(new Integer("12138"),"Mato Castelhano", new Integer("43")));
        lista.add(new Municipio(new Integer("12153"),"Mato Leitão", new Integer("43")));
        lista.add(new Municipio(new Integer("12179"),"Mato Queimado", new Integer("43")));
        lista.add(new Municipio(new Integer("12203"),"Maximiliano de Almeida", new Integer("43")));
        lista.add(new Municipio(new Integer("12252"),"Minas do Leão", new Integer("43")));
        lista.add(new Municipio(new Integer("12302"),"Miraguaí", new Integer("43")));
        lista.add(new Municipio(new Integer("12351"),"Montauri", new Integer("43")));
        lista.add(new Municipio(new Integer("12377"),"Monte Alegre dos Campos", new Integer("43")));
        lista.add(new Municipio(new Integer("12385"),"Monte Belo do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("12401"),"Montenegro", new Integer("43")));
        lista.add(new Municipio(new Integer("12427"),"Mormaço", new Integer("43")));
        lista.add(new Municipio(new Integer("12443"),"Morrinhos do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("12450"),"Morro Redondo", new Integer("43")));
        lista.add(new Municipio(new Integer("12476"),"Morro Reuter", new Integer("43")));
        lista.add(new Municipio(new Integer("12500"),"Mostardas", new Integer("43")));
        lista.add(new Municipio(new Integer("12609"),"Muçum", new Integer("43")));
        lista.add(new Municipio(new Integer("12617"),"Muitos Capões", new Integer("43")));
        lista.add(new Municipio(new Integer("12625"),"Muliterno", new Integer("43")));
        lista.add(new Municipio(new Integer("12658"),"Não-Me-Toque", new Integer("43")));
        lista.add(new Municipio(new Integer("12674"),"Nicolau Vergueiro", new Integer("43")));
        lista.add(new Municipio(new Integer("12708"),"Nonoai", new Integer("43")));
        lista.add(new Municipio(new Integer("12757"),"Nova Alvorada", new Integer("43")));
        lista.add(new Municipio(new Integer("12807"),"Nova Araçá", new Integer("43")));
        lista.add(new Municipio(new Integer("12906"),"Nova Bassano", new Integer("43")));
        lista.add(new Municipio(new Integer("12955"),"Nova Boa Vista", new Integer("43")));
        lista.add(new Municipio(new Integer("13003"),"Nova Bréscia", new Integer("43")));
        lista.add(new Municipio(new Integer("13011"),"Nova Candelária", new Integer("43")));
        lista.add(new Municipio(new Integer("13037"),"Nova Esperança do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("13060"),"Nova Hartz", new Integer("43")));
        lista.add(new Municipio(new Integer("13086"),"Nova Pádua", new Integer("43")));
        lista.add(new Municipio(new Integer("13102"),"Nova Palma", new Integer("43")));
        lista.add(new Municipio(new Integer("13201"),"Nova Petrópolis", new Integer("43")));
        lista.add(new Municipio(new Integer("13300"),"Nova Prata", new Integer("43")));
        lista.add(new Municipio(new Integer("13334"),"Nova Ramada", new Integer("43")));
        lista.add(new Municipio(new Integer("13359"),"Nova Roma do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("13375"),"Nova Santa Rita", new Integer("43")));
        lista.add(new Municipio(new Integer("13391"),"Novo Cabrais", new Integer("43")));
        lista.add(new Municipio(new Integer("13409"),"Novo Hamburgo", new Integer("43")));
        lista.add(new Municipio(new Integer("13425"),"Novo Machado", new Integer("43")));
        lista.add(new Municipio(new Integer("13441"),"Novo Tiradentes", new Integer("43")));
        lista.add(new Municipio(new Integer("13466"),"Novo Xingu", new Integer("43")));
        lista.add(new Municipio(new Integer("13490"),"Novo Barreiro", new Integer("43")));
        lista.add(new Municipio(new Integer("13508"),"Osório", new Integer("43")));
        lista.add(new Municipio(new Integer("13607"),"Paim Filho", new Integer("43")));
        lista.add(new Municipio(new Integer("13656"),"Palmares do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("13706"),"Palmeira das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("13805"),"Palmitinho", new Integer("43")));
        lista.add(new Municipio(new Integer("13904"),"Panambi", new Integer("43")));
        lista.add(new Municipio(new Integer("13953"),"Pantano Grande", new Integer("43")));
        lista.add(new Municipio(new Integer("14001"),"Paraí", new Integer("43")));
        lista.add(new Municipio(new Integer("14027"),"Paraíso do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("14035"),"Pareci Novo", new Integer("43")));
        lista.add(new Municipio(new Integer("14050"),"Parobé", new Integer("43")));
        lista.add(new Municipio(new Integer("14068"),"Passa Sete", new Integer("43")));
        lista.add(new Municipio(new Integer("14076"),"Passo do Sobrado", new Integer("43")));
        lista.add(new Municipio(new Integer("14100"),"Passo Fundo", new Integer("43")));
        lista.add(new Municipio(new Integer("14134"),"Paulo Bento", new Integer("43")));
        lista.add(new Municipio(new Integer("14159"),"Paverama", new Integer("43")));
        lista.add(new Municipio(new Integer("14175"),"Pedras Altas", new Integer("43")));
        lista.add(new Municipio(new Integer("14209"),"Pedro Osório", new Integer("43")));
        lista.add(new Municipio(new Integer("14308"),"Pejuçara", new Integer("43")));
        lista.add(new Municipio(new Integer("14407"),"Pelotas", new Integer("43")));
        lista.add(new Municipio(new Integer("14423"),"Picada Café", new Integer("43")));
        lista.add(new Municipio(new Integer("14456"),"Pinhal", new Integer("43")));
        lista.add(new Municipio(new Integer("14464"),"Pinhal da Serra", new Integer("43")));
        lista.add(new Municipio(new Integer("14472"),"Pinhal Grande", new Integer("43")));
        lista.add(new Municipio(new Integer("14498"),"Pinheirinho do Vale", new Integer("43")));
        lista.add(new Municipio(new Integer("14506"),"Pinheiro Machado", new Integer("43")));
        lista.add(new Municipio(new Integer("14548"),"Pinto Bandeira", new Integer("43")));
        lista.add(new Municipio(new Integer("14555"),"Pirapó", new Integer("43")));
        lista.add(new Municipio(new Integer("14605"),"Piratini", new Integer("43")));
        lista.add(new Municipio(new Integer("14704"),"Planalto", new Integer("43")));
        lista.add(new Municipio(new Integer("14753"),"Poço das Antas", new Integer("43")));
        lista.add(new Municipio(new Integer("14779"),"Pontão", new Integer("43")));
        lista.add(new Municipio(new Integer("14787"),"Ponte Preta", new Integer("43")));
        lista.add(new Municipio(new Integer("14803"),"Portão", new Integer("43")));
        lista.add(new Municipio(new Integer("14902"),"Porto Alegre", new Integer("43")));
        lista.add(new Municipio(new Integer("15008"),"Porto Lucena", new Integer("43")));
        lista.add(new Municipio(new Integer("15057"),"Porto Mauá", new Integer("43")));
        lista.add(new Municipio(new Integer("15073"),"Porto Vera Cruz", new Integer("43")));
        lista.add(new Municipio(new Integer("15107"),"Porto Xavier", new Integer("43")));
        lista.add(new Municipio(new Integer("15131"),"Pouso Novo", new Integer("43")));
        lista.add(new Municipio(new Integer("15149"),"Presidente Lucena", new Integer("43")));
        lista.add(new Municipio(new Integer("15156"),"Progresso", new Integer("43")));
        lista.add(new Municipio(new Integer("15172"),"Protásio Alves", new Integer("43")));
        lista.add(new Municipio(new Integer("15206"),"Putinga", new Integer("43")));
        lista.add(new Municipio(new Integer("15305"),"Quaraí", new Integer("43")));
        lista.add(new Municipio(new Integer("15313"),"Quatro Irmãos", new Integer("43")));
        lista.add(new Municipio(new Integer("15321"),"Quevedos", new Integer("43")));
        lista.add(new Municipio(new Integer("15354"),"Quinze de Novembro", new Integer("43")));
        lista.add(new Municipio(new Integer("15404"),"Redentora", new Integer("43")));
        lista.add(new Municipio(new Integer("15453"),"Relvado", new Integer("43")));
        lista.add(new Municipio(new Integer("15503"),"Restinga Seca", new Integer("43")));
        lista.add(new Municipio(new Integer("15552"),"Rio dos Índios", new Integer("43")));
        lista.add(new Municipio(new Integer("15602"),"Rio Grande", new Integer("43")));
        lista.add(new Municipio(new Integer("15701"),"Rio Pardo", new Integer("43")));
        lista.add(new Municipio(new Integer("15750"),"Riozinho", new Integer("43")));
        lista.add(new Municipio(new Integer("15800"),"Roca Sales", new Integer("43")));
        lista.add(new Municipio(new Integer("15909"),"Rodeio Bonito", new Integer("43")));
        lista.add(new Municipio(new Integer("15958"),"Rolador", new Integer("43")));
        lista.add(new Municipio(new Integer("16006"),"Rolante", new Integer("43")));
        lista.add(new Municipio(new Integer("16105"),"Ronda Alta", new Integer("43")));
        lista.add(new Municipio(new Integer("16204"),"Rondinha", new Integer("43")));
        lista.add(new Municipio(new Integer("16303"),"Roque Gonzales", new Integer("43")));
        lista.add(new Municipio(new Integer("16402"),"Rosário do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("16428"),"Sagrada Família", new Integer("43")));
        lista.add(new Municipio(new Integer("16436"),"Saldanha Marinho", new Integer("43")));
        lista.add(new Municipio(new Integer("16451"),"Salto do Jacuí", new Integer("43")));
        lista.add(new Municipio(new Integer("16477"),"Salvador das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("16501"),"Salvador do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("16600"),"Sananduva", new Integer("43")));
        lista.add(new Municipio(new Integer("16709"),"Santa Bárbara do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("16733"),"Santa Cecília do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("16758"),"Santa Clara do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("16808"),"Santa Cruz do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("16907"),"Santa Maria", new Integer("43")));
        lista.add(new Municipio(new Integer("16956"),"Santa Maria do Herval", new Integer("43")));
        lista.add(new Municipio(new Integer("16972"),"Santa Margarida do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("17004"),"Santana da Boa Vista", new Integer("43")));
        lista.add(new Municipio(new Integer("17103"),"Sant'Ana do Livramento", new Integer("43")));
        lista.add(new Municipio(new Integer("17202"),"Santa Rosa", new Integer("43")));
        lista.add(new Municipio(new Integer("17251"),"Santa Tereza", new Integer("43")));
        lista.add(new Municipio(new Integer("17301"),"Santa Vitória do Palmar", new Integer("43")));
        lista.add(new Municipio(new Integer("17400"),"Santiago", new Integer("43")));
        lista.add(new Municipio(new Integer("17509"),"Santo Ângelo", new Integer("43")));
        lista.add(new Municipio(new Integer("17558"),"Santo Antônio do Palma", new Integer("43")));
        lista.add(new Municipio(new Integer("17608"),"Santo Antônio da Patrulha", new Integer("43")));
        lista.add(new Municipio(new Integer("17707"),"Santo Antônio das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("17756"),"Santo Antônio do Planalto", new Integer("43")));
        lista.add(new Municipio(new Integer("17806"),"Santo Augusto", new Integer("43")));
        lista.add(new Municipio(new Integer("17905"),"Santo Cristo", new Integer("43")));
        lista.add(new Municipio(new Integer("17954"),"Santo Expedito do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("18002"),"São Borja", new Integer("43")));
        lista.add(new Municipio(new Integer("18051"),"São Domingos do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("18101"),"São Francisco de Assis", new Integer("43")));
        lista.add(new Municipio(new Integer("18200"),"São Francisco de Paula", new Integer("43")));
        lista.add(new Municipio(new Integer("18309"),"São Gabriel", new Integer("43")));
        lista.add(new Municipio(new Integer("18408"),"São Jerônimo", new Integer("43")));
        lista.add(new Municipio(new Integer("18424"),"São João da Urtiga", new Integer("43")));
        lista.add(new Municipio(new Integer("18432"),"São João do Polêsine", new Integer("43")));
        lista.add(new Municipio(new Integer("18440"),"São Jorge", new Integer("43")));
        lista.add(new Municipio(new Integer("18457"),"São José das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("18465"),"São José do Herval", new Integer("43")));
        lista.add(new Municipio(new Integer("18481"),"São José do Hortêncio", new Integer("43")));
        lista.add(new Municipio(new Integer("18499"),"São José do Inhacorá", new Integer("43")));
        lista.add(new Municipio(new Integer("18507"),"São José do Norte", new Integer("43")));
        lista.add(new Municipio(new Integer("18606"),"São José do Ouro", new Integer("43")));
        lista.add(new Municipio(new Integer("18614"),"São José do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("18622"),"São José dos Ausentes", new Integer("43")));
        lista.add(new Municipio(new Integer("18705"),"São Leopoldo", new Integer("43")));
        lista.add(new Municipio(new Integer("18804"),"São Lourenço do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("18903"),"São Luiz Gonzaga", new Integer("43")));
        lista.add(new Municipio(new Integer("19000"),"São Marcos", new Integer("43")));
        lista.add(new Municipio(new Integer("19109"),"São Martinho", new Integer("43")));
        lista.add(new Municipio(new Integer("19125"),"São Martinho da Serra", new Integer("43")));
        lista.add(new Municipio(new Integer("19158"),"São Miguel das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("19208"),"São Nicolau", new Integer("43")));
        lista.add(new Municipio(new Integer("19307"),"São Paulo das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("19356"),"São Pedro da Serra", new Integer("43")));
        lista.add(new Municipio(new Integer("19364"),"São Pedro das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("19372"),"São Pedro do Butiá", new Integer("43")));
        lista.add(new Municipio(new Integer("19406"),"São Pedro do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("19505"),"São Sebastião do Caí", new Integer("43")));
        lista.add(new Municipio(new Integer("19604"),"São Sepé", new Integer("43")));
        lista.add(new Municipio(new Integer("19703"),"São Valentim", new Integer("43")));
        lista.add(new Municipio(new Integer("19711"),"São Valentim do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("19737"),"São Valério do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("19752"),"São Vendelino", new Integer("43")));
        lista.add(new Municipio(new Integer("19802"),"São Vicente do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("19901"),"Sapiranga", new Integer("43")));
        lista.add(new Municipio(new Integer("20008"),"Sapucaia do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("20107"),"Sarandi", new Integer("43")));
        lista.add(new Municipio(new Integer("20206"),"Seberi", new Integer("43")));
        lista.add(new Municipio(new Integer("20230"),"Sede Nova", new Integer("43")));
        lista.add(new Municipio(new Integer("20263"),"Segredo", new Integer("43")));
        lista.add(new Municipio(new Integer("20305"),"Selbach", new Integer("43")));
        lista.add(new Municipio(new Integer("20321"),"Senador Salgado Filho", new Integer("43")));
        lista.add(new Municipio(new Integer("20354"),"Sentinela do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("20404"),"Serafina Corrêa", new Integer("43")));
        lista.add(new Municipio(new Integer("20453"),"Sério", new Integer("43")));
        lista.add(new Municipio(new Integer("20503"),"Sertão", new Integer("43")));
        lista.add(new Municipio(new Integer("20552"),"Sertão Santana", new Integer("43")));
        lista.add(new Municipio(new Integer("20578"),"Sete de Setembro", new Integer("43")));
        lista.add(new Municipio(new Integer("20602"),"Severiano de Almeida", new Integer("43")));
        lista.add(new Municipio(new Integer("20651"),"Silveira Martins", new Integer("43")));
        lista.add(new Municipio(new Integer("20677"),"Sinimbu", new Integer("43")));
        lista.add(new Municipio(new Integer("20701"),"Sobradinho", new Integer("43")));
        lista.add(new Municipio(new Integer("20800"),"Soledade", new Integer("43")));
        lista.add(new Municipio(new Integer("20859"),"Tabaí", new Integer("43")));
        lista.add(new Municipio(new Integer("20909"),"Tapejara", new Integer("43")));
        lista.add(new Municipio(new Integer("21006"),"Tapera", new Integer("43")));
        lista.add(new Municipio(new Integer("21105"),"Tapes", new Integer("43")));
        lista.add(new Municipio(new Integer("21204"),"Taquara", new Integer("43")));
        lista.add(new Municipio(new Integer("21303"),"Taquari", new Integer("43")));
        lista.add(new Municipio(new Integer("21329"),"Taquaruçu do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("21352"),"Tavares", new Integer("43")));
        lista.add(new Municipio(new Integer("21402"),"Tenente Portela", new Integer("43")));
        lista.add(new Municipio(new Integer("21436"),"Terra de Areia", new Integer("43")));
        lista.add(new Municipio(new Integer("21451"),"Teutônia", new Integer("43")));
        lista.add(new Municipio(new Integer("21469"),"Tio Hugo", new Integer("43")));
        lista.add(new Municipio(new Integer("21477"),"Tiradentes do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("21493"),"Toropi", new Integer("43")));
        lista.add(new Municipio(new Integer("21501"),"Torres", new Integer("43")));
        lista.add(new Municipio(new Integer("21600"),"Tramandaí", new Integer("43")));
        lista.add(new Municipio(new Integer("21626"),"Travesseiro", new Integer("43")));
        lista.add(new Municipio(new Integer("21634"),"Três Arroios", new Integer("43")));
        lista.add(new Municipio(new Integer("21667"),"Três Cachoeiras", new Integer("43")));
        lista.add(new Municipio(new Integer("21709"),"Três Coroas", new Integer("43")));
        lista.add(new Municipio(new Integer("21808"),"Três de Maio", new Integer("43")));
        lista.add(new Municipio(new Integer("21832"),"Três Forquilhas", new Integer("43")));
        lista.add(new Municipio(new Integer("21857"),"Três Palmeiras", new Integer("43")));
        lista.add(new Municipio(new Integer("21907"),"Três Passos", new Integer("43")));
        lista.add(new Municipio(new Integer("21956"),"Trindade do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("22004"),"Triunfo", new Integer("43")));
        lista.add(new Municipio(new Integer("22103"),"Tucunduva", new Integer("43")));
        lista.add(new Municipio(new Integer("22152"),"Tunas", new Integer("43")));
        lista.add(new Municipio(new Integer("22186"),"Tupanci do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("22202"),"Tupanciretã", new Integer("43")));
        lista.add(new Municipio(new Integer("22251"),"Tupandi", new Integer("43")));
        lista.add(new Municipio(new Integer("22301"),"Tuparendi", new Integer("43")));
        lista.add(new Municipio(new Integer("22327"),"Turuçu", new Integer("43")));
        lista.add(new Municipio(new Integer("22343"),"Ubiretama", new Integer("43")));
        lista.add(new Municipio(new Integer("22350"),"União da Serra", new Integer("43")));
        lista.add(new Municipio(new Integer("22376"),"Unistalda", new Integer("43")));
        lista.add(new Municipio(new Integer("22400"),"Uruguaiana", new Integer("43")));
        lista.add(new Municipio(new Integer("22509"),"Vacaria", new Integer("43")));
        lista.add(new Municipio(new Integer("22525"),"Vale Verde", new Integer("43")));
        lista.add(new Municipio(new Integer("22533"),"Vale do Sol", new Integer("43")));
        lista.add(new Municipio(new Integer("22541"),"Vale Real", new Integer("43")));
        lista.add(new Municipio(new Integer("22558"),"Vanini", new Integer("43")));
        lista.add(new Municipio(new Integer("22608"),"Venâncio Aires", new Integer("43")));
        lista.add(new Municipio(new Integer("22707"),"Vera Cruz", new Integer("43")));
        lista.add(new Municipio(new Integer("22806"),"Veranópolis", new Integer("43")));
        lista.add(new Municipio(new Integer("22855"),"Vespasiano Correa", new Integer("43")));
        lista.add(new Municipio(new Integer("22905"),"Viadutos", new Integer("43")));
        lista.add(new Municipio(new Integer("23002"),"Viamão", new Integer("43")));
        lista.add(new Municipio(new Integer("23101"),"Vicente Dutra", new Integer("43")));
        lista.add(new Municipio(new Integer("23200"),"Victor Graeff", new Integer("43")));
        lista.add(new Municipio(new Integer("23309"),"Vila Flores", new Integer("43")));
        lista.add(new Municipio(new Integer("23358"),"Vila Lângaro", new Integer("43")));
        lista.add(new Municipio(new Integer("23408"),"Vila Maria", new Integer("43")));
        lista.add(new Municipio(new Integer("23457"),"Vila Nova do Sul", new Integer("43")));
        lista.add(new Municipio(new Integer("23507"),"Vista Alegre", new Integer("43")));
        lista.add(new Municipio(new Integer("23606"),"Vista Alegre do Prata", new Integer("43")));
        lista.add(new Municipio(new Integer("23705"),"Vista Gaúcha", new Integer("43")));
        lista.add(new Municipio(new Integer("23754"),"Vitória das Missões", new Integer("43")));
        lista.add(new Municipio(new Integer("23770"),"Westfalia", new Integer("43")));
        lista.add(new Municipio(new Integer("23804"),"Xangri-lá", new Integer("43")));

        lista.add(new Municipio(new Integer("00203"),"Água Clara", new Integer("50")));
        lista.add(new Municipio(new Integer("00252"),"Alcinópolis", new Integer("50")));
        lista.add(new Municipio(new Integer("00609"),"Amambai", new Integer("50")));
        lista.add(new Municipio(new Integer("00708"),"Anastácio", new Integer("50")));
        lista.add(new Municipio(new Integer("00807"),"Anaurilândia", new Integer("50")));
        lista.add(new Municipio(new Integer("00856"),"Angélica", new Integer("50")));
        lista.add(new Municipio(new Integer("00906"),"Antônio João", new Integer("50")));
        lista.add(new Municipio(new Integer("01003"),"Aparecida do Taboado", new Integer("50")));
        lista.add(new Municipio(new Integer("01102"),"Aquidauana", new Integer("50")));
        lista.add(new Municipio(new Integer("01243"),"Aral Moreira", new Integer("50")));
        lista.add(new Municipio(new Integer("01508"),"Bandeirantes", new Integer("50")));
        lista.add(new Municipio(new Integer("01904"),"Bataguassu", new Integer("50")));
        lista.add(new Municipio(new Integer("02001"),"Batayporã", new Integer("50")));
        lista.add(new Municipio(new Integer("02100"),"Bela Vista", new Integer("50")));
        lista.add(new Municipio(new Integer("02159"),"Bodoquena", new Integer("50")));
        lista.add(new Municipio(new Integer("02209"),"Bonito", new Integer("50")));
        lista.add(new Municipio(new Integer("02308"),"Brasilândia", new Integer("50")));
        lista.add(new Municipio(new Integer("02407"),"Caarapó", new Integer("50")));
        lista.add(new Municipio(new Integer("02605"),"Camapuã", new Integer("50")));
        lista.add(new Municipio(new Integer("02704"),"Campo Grande", new Integer("50")));
        lista.add(new Municipio(new Integer("02803"),"Caracol", new Integer("50")));
        lista.add(new Municipio(new Integer("02902"),"Cassilândia", new Integer("50")));
        lista.add(new Municipio(new Integer("02951"),"Chapadão do Sul", new Integer("50")));
        lista.add(new Municipio(new Integer("03108"),"Corguinho", new Integer("50")));
        lista.add(new Municipio(new Integer("03157"),"Coronel Sapucaia", new Integer("50")));
        lista.add(new Municipio(new Integer("03207"),"Corumbá", new Integer("50")));
        lista.add(new Municipio(new Integer("03256"),"Costa Rica", new Integer("50")));
        lista.add(new Municipio(new Integer("03306"),"Coxim", new Integer("50")));
        lista.add(new Municipio(new Integer("03454"),"Deodápolis", new Integer("50")));
        lista.add(new Municipio(new Integer("03488"),"Dois Irmãos do Buriti", new Integer("50")));
        lista.add(new Municipio(new Integer("03504"),"Douradina", new Integer("50")));
        lista.add(new Municipio(new Integer("03702"),"Dourados", new Integer("50")));
        lista.add(new Municipio(new Integer("03751"),"Eldorado", new Integer("50")));
        lista.add(new Municipio(new Integer("03801"),"Fátima do Sul", new Integer("50")));
        lista.add(new Municipio(new Integer("03900"),"Figueirão", new Integer("50")));
        lista.add(new Municipio(new Integer("04007"),"Glória de Dourados", new Integer("50")));
        lista.add(new Municipio(new Integer("04106"),"Guia Lopes da Laguna", new Integer("50")));
        lista.add(new Municipio(new Integer("04304"),"Iguatemi", new Integer("50")));
        lista.add(new Municipio(new Integer("04403"),"Inocência", new Integer("50")));
        lista.add(new Municipio(new Integer("04502"),"Itaporã", new Integer("50")));
        lista.add(new Municipio(new Integer("04601"),"Itaquiraí", new Integer("50")));
        lista.add(new Municipio(new Integer("04700"),"Ivinhema", new Integer("50")));
        lista.add(new Municipio(new Integer("04809"),"Japorã", new Integer("50")));
        lista.add(new Municipio(new Integer("04908"),"Jaraguari", new Integer("50")));
        lista.add(new Municipio(new Integer("05004"),"Jardim", new Integer("50")));
        lista.add(new Municipio(new Integer("05103"),"Jateí", new Integer("50")));
        lista.add(new Municipio(new Integer("05152"),"Juti", new Integer("50")));
        lista.add(new Municipio(new Integer("05202"),"Ladário", new Integer("50")));
        lista.add(new Municipio(new Integer("05251"),"Laguna Carapã", new Integer("50")));
        lista.add(new Municipio(new Integer("05400"),"Maracaju", new Integer("50")));
        lista.add(new Municipio(new Integer("05608"),"Miranda", new Integer("50")));
        lista.add(new Municipio(new Integer("05681"),"Mundo Novo", new Integer("50")));
        lista.add(new Municipio(new Integer("05707"),"Naviraí", new Integer("50")));
        lista.add(new Municipio(new Integer("05806"),"Nioaque", new Integer("50")));
        lista.add(new Municipio(new Integer("06002"),"Nova Alvorada do Sul", new Integer("50")));
        lista.add(new Municipio(new Integer("06200"),"Nova Andradina", new Integer("50")));
        lista.add(new Municipio(new Integer("06259"),"Novo Horizonte do Sul", new Integer("50")));
        lista.add(new Municipio(new Integer("06275"),"Paraíso das Águas", new Integer("50")));
        lista.add(new Municipio(new Integer("06309"),"Paranaíba", new Integer("50")));
        lista.add(new Municipio(new Integer("06358"),"Paranhos", new Integer("50")));
        lista.add(new Municipio(new Integer("06408"),"Pedro Gomes", new Integer("50")));
        lista.add(new Municipio(new Integer("06606"),"Ponta Porã", new Integer("50")));
        lista.add(new Municipio(new Integer("06903"),"Porto Murtinho", new Integer("50")));
        lista.add(new Municipio(new Integer("07109"),"Ribas do Rio Pardo", new Integer("50")));
        lista.add(new Municipio(new Integer("07208"),"Rio Brilhante", new Integer("50")));
        lista.add(new Municipio(new Integer("07307"),"Rio Negro", new Integer("50")));
        lista.add(new Municipio(new Integer("07406"),"Rio Verde de Mato Grosso", new Integer("50")));
        lista.add(new Municipio(new Integer("07505"),"Rochedo", new Integer("50")));
        lista.add(new Municipio(new Integer("07554"),"Santa Rita do Pardo", new Integer("50")));
        lista.add(new Municipio(new Integer("07695"),"São Gabriel do Oeste", new Integer("50")));
        lista.add(new Municipio(new Integer("07703"),"Sete Quedas", new Integer("50")));
        lista.add(new Municipio(new Integer("07802"),"Selvíria", new Integer("50")));
        lista.add(new Municipio(new Integer("07901"),"Sidrolândia", new Integer("50")));
        lista.add(new Municipio(new Integer("07935"),"Sonora", new Integer("50")));
        lista.add(new Municipio(new Integer("07950"),"Tacuru", new Integer("50")));
        lista.add(new Municipio(new Integer("07976"),"Taquarussu", new Integer("50")));
        lista.add(new Municipio(new Integer("08008"),"Terenos", new Integer("50")));
        lista.add(new Municipio(new Integer("08305"),"Três Lagoas", new Integer("50")));
        lista.add(new Municipio(new Integer("08404"),"Vicentina", new Integer("50")));

        lista.add(new Municipio(new Integer("00102"),"Acorizal", new Integer("51")));
        lista.add(new Municipio(new Integer("00201"),"Água Boa", new Integer("51")));
        lista.add(new Municipio(new Integer("00250"),"Alta Floresta", new Integer("51")));
        lista.add(new Municipio(new Integer("00300"),"Alto Araguaia", new Integer("51")));
        lista.add(new Municipio(new Integer("00359"),"Alto Boa Vista", new Integer("51")));
        lista.add(new Municipio(new Integer("00409"),"Alto Garças", new Integer("51")));
        lista.add(new Municipio(new Integer("00508"),"Alto Paraguai", new Integer("51")));
        lista.add(new Municipio(new Integer("00607"),"Alto Taquari", new Integer("51")));
        lista.add(new Municipio(new Integer("00805"),"Apiacás", new Integer("51")));
        lista.add(new Municipio(new Integer("01001"),"Araguaiana", new Integer("51")));
        lista.add(new Municipio(new Integer("01209"),"Araguainha", new Integer("51")));
        lista.add(new Municipio(new Integer("01258"),"Araputanga", new Integer("51")));
        lista.add(new Municipio(new Integer("01308"),"Arenápolis", new Integer("51")));
        lista.add(new Municipio(new Integer("01407"),"Aripuanã", new Integer("51")));
        lista.add(new Municipio(new Integer("01605"),"Barão de Melgaço", new Integer("51")));
        lista.add(new Municipio(new Integer("01704"),"Barra do Bugres", new Integer("51")));
        lista.add(new Municipio(new Integer("01803"),"Barra do Garças", new Integer("51")));
        lista.add(new Municipio(new Integer("01852"),"Bom Jesus do Araguaia", new Integer("51")));
        lista.add(new Municipio(new Integer("01902"),"Brasnorte", new Integer("51")));
        lista.add(new Municipio(new Integer("02504"),"Cáceres", new Integer("51")));
        lista.add(new Municipio(new Integer("02603"),"Campinápolis", new Integer("51")));
        lista.add(new Municipio(new Integer("02637"),"Campo Novo do Parecis", new Integer("51")));
        lista.add(new Municipio(new Integer("02678"),"Campo Verde", new Integer("51")));
        lista.add(new Municipio(new Integer("02686"),"Campos de Júlio", new Integer("51")));
        lista.add(new Municipio(new Integer("02694"),"Canabrava do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("02702"),"Canarana", new Integer("51")));
        lista.add(new Municipio(new Integer("02793"),"Carlinda", new Integer("51")));
        lista.add(new Municipio(new Integer("02850"),"Castanheira", new Integer("51")));
        lista.add(new Municipio(new Integer("03007"),"Chapada dos Guimarães", new Integer("51")));
        lista.add(new Municipio(new Integer("03056"),"Cláudia", new Integer("51")));
        lista.add(new Municipio(new Integer("03106"),"Cocalinho", new Integer("51")));
        lista.add(new Municipio(new Integer("03205"),"Colíder", new Integer("51")));
        lista.add(new Municipio(new Integer("03254"),"Colniza", new Integer("51")));
        lista.add(new Municipio(new Integer("03304"),"Comodoro", new Integer("51")));
        lista.add(new Municipio(new Integer("03353"),"Confresa", new Integer("51")));
        lista.add(new Municipio(new Integer("03361"),"Conquista D'Oeste", new Integer("51")));
        lista.add(new Municipio(new Integer("03379"),"Cotriguaçu", new Integer("51")));
        lista.add(new Municipio(new Integer("03403"),"Cuiabá", new Integer("51")));
        lista.add(new Municipio(new Integer("03437"),"Curvelândia", new Integer("51")));
        lista.add(new Municipio(new Integer("03452"),"Denise", new Integer("51")));
        lista.add(new Municipio(new Integer("03502"),"Diamantino", new Integer("51")));
        lista.add(new Municipio(new Integer("03601"),"Dom Aquino", new Integer("51")));
        lista.add(new Municipio(new Integer("03700"),"Feliz Natal", new Integer("51")));
        lista.add(new Municipio(new Integer("03809"),"Figueirópolis D'Oeste", new Integer("51")));
        lista.add(new Municipio(new Integer("03858"),"Gaúcha do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("03908"),"General Carneiro", new Integer("51")));
        lista.add(new Municipio(new Integer("03957"),"Glória D'Oeste", new Integer("51")));
        lista.add(new Municipio(new Integer("04104"),"Guarantã do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("04203"),"Guiratinga", new Integer("51")));
        lista.add(new Municipio(new Integer("04500"),"Indiavaí", new Integer("51")));
        lista.add(new Municipio(new Integer("04526"),"Ipiranga do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("04542"),"Itanhangá", new Integer("51")));
        lista.add(new Municipio(new Integer("04559"),"Itaúba", new Integer("51")));
        lista.add(new Municipio(new Integer("04609"),"Itiquira", new Integer("51")));
        lista.add(new Municipio(new Integer("04807"),"Jaciara", new Integer("51")));
        lista.add(new Municipio(new Integer("04906"),"Jangada", new Integer("51")));
        lista.add(new Municipio(new Integer("05002"),"Jauru", new Integer("51")));
        lista.add(new Municipio(new Integer("05101"),"Juara", new Integer("51")));
        lista.add(new Municipio(new Integer("05150"),"Juína", new Integer("51")));
        lista.add(new Municipio(new Integer("05176"),"Juruena", new Integer("51")));
        lista.add(new Municipio(new Integer("05200"),"Juscimeira", new Integer("51")));
        lista.add(new Municipio(new Integer("05234"),"Lambari D'Oeste", new Integer("51")));
        lista.add(new Municipio(new Integer("05259"),"Lucas do Rio Verde", new Integer("51")));
        lista.add(new Municipio(new Integer("05309"),"Luciara", new Integer("51")));
        lista.add(new Municipio(new Integer("05507"),"Vila Bela da Santíssima Trindade", new Integer("51")));
        lista.add(new Municipio(new Integer("05580"),"Marcelândia", new Integer("51")));
        lista.add(new Municipio(new Integer("05606"),"Matupá", new Integer("51")));
        lista.add(new Municipio(new Integer("05622"),"Mirassol d'Oeste", new Integer("51")));
        lista.add(new Municipio(new Integer("05903"),"Nobres", new Integer("51")));
        lista.add(new Municipio(new Integer("06000"),"Nortelândia", new Integer("51")));
        lista.add(new Municipio(new Integer("06109"),"Nossa Senhora do Livramento", new Integer("51")));
        lista.add(new Municipio(new Integer("06158"),"Nova Bandeirantes", new Integer("51")));
        lista.add(new Municipio(new Integer("06174"),"Nova Nazaré", new Integer("51")));
        lista.add(new Municipio(new Integer("06182"),"Nova Lacerda", new Integer("51")));
        lista.add(new Municipio(new Integer("06190"),"Nova Santa Helena", new Integer("51")));
        lista.add(new Municipio(new Integer("06208"),"Nova Brasilândia", new Integer("51")));
        lista.add(new Municipio(new Integer("06216"),"Nova Canaã do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("06224"),"Nova Mutum", new Integer("51")));
        lista.add(new Municipio(new Integer("06232"),"Nova Olímpia", new Integer("51")));
        lista.add(new Municipio(new Integer("06240"),"Nova Ubiratã", new Integer("51")));
        lista.add(new Municipio(new Integer("06257"),"Nova Xavantina", new Integer("51")));
        lista.add(new Municipio(new Integer("06265"),"Novo Mundo", new Integer("51")));
        lista.add(new Municipio(new Integer("06273"),"Novo Horizonte do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("06281"),"Novo São Joaquim", new Integer("51")));
        lista.add(new Municipio(new Integer("06299"),"Paranaíta", new Integer("51")));
        lista.add(new Municipio(new Integer("06307"),"Paranatinga", new Integer("51")));
        lista.add(new Municipio(new Integer("06315"),"Novo Santo Antônio", new Integer("51")));
        lista.add(new Municipio(new Integer("06372"),"Pedra Preta", new Integer("51")));
        lista.add(new Municipio(new Integer("06422"),"Peixoto de Azevedo", new Integer("51")));
        lista.add(new Municipio(new Integer("06455"),"Planalto da Serra", new Integer("51")));
        lista.add(new Municipio(new Integer("06505"),"Poconé", new Integer("51")));
        lista.add(new Municipio(new Integer("06653"),"Pontal do Araguaia", new Integer("51")));
        lista.add(new Municipio(new Integer("06703"),"Ponte Branca", new Integer("51")));
        lista.add(new Municipio(new Integer("06752"),"Pontes e Lacerda", new Integer("51")));
        lista.add(new Municipio(new Integer("06778"),"Porto Alegre do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("06802"),"Porto dos Gaúchos", new Integer("51")));
        lista.add(new Municipio(new Integer("06828"),"Porto Esperidião", new Integer("51")));
        lista.add(new Municipio(new Integer("06851"),"Porto Estrela", new Integer("51")));
        lista.add(new Municipio(new Integer("07008"),"Poxoréo", new Integer("51")));
        lista.add(new Municipio(new Integer("07040"),"Primavera do Leste", new Integer("51")));
        lista.add(new Municipio(new Integer("07065"),"Querência", new Integer("51")));
        lista.add(new Municipio(new Integer("07107"),"São José dos Quatro Marcos", new Integer("51")));
        lista.add(new Municipio(new Integer("07156"),"Reserva do Cabaçal", new Integer("51")));
        lista.add(new Municipio(new Integer("07180"),"Ribeirão Cascalheira", new Integer("51")));
        lista.add(new Municipio(new Integer("07198"),"Ribeirãozinho", new Integer("51")));
        lista.add(new Municipio(new Integer("07206"),"Rio Branco", new Integer("51")));
        lista.add(new Municipio(new Integer("07248"),"Santa Carmem", new Integer("51")));
        lista.add(new Municipio(new Integer("07263"),"Santo Afonso", new Integer("51")));
        lista.add(new Municipio(new Integer("07297"),"São José do Povo", new Integer("51")));
        lista.add(new Municipio(new Integer("07305"),"São José do Rio Claro", new Integer("51")));
        lista.add(new Municipio(new Integer("07354"),"São José do Xingu", new Integer("51")));
        lista.add(new Municipio(new Integer("07404"),"São Pedro da Cipa", new Integer("51")));
        lista.add(new Municipio(new Integer("07578"),"Rondolândia", new Integer("51")));
        lista.add(new Municipio(new Integer("07602"),"Rondonópolis", new Integer("51")));
        lista.add(new Municipio(new Integer("07701"),"Rosário Oeste", new Integer("51")));
        lista.add(new Municipio(new Integer("07743"),"Santa Cruz do Xingu", new Integer("51")));
        lista.add(new Municipio(new Integer("07750"),"Salto do Céu", new Integer("51")));
        lista.add(new Municipio(new Integer("07768"),"Santa Rita do Trivelato", new Integer("51")));
        lista.add(new Municipio(new Integer("07776"),"Santa Terezinha", new Integer("51")));
        lista.add(new Municipio(new Integer("07792"),"Santo Antônio do Leste", new Integer("51")));
        lista.add(new Municipio(new Integer("07800"),"Santo Antônio do Leverger", new Integer("51")));
        lista.add(new Municipio(new Integer("07859"),"São Félix do Araguaia", new Integer("51")));
        lista.add(new Municipio(new Integer("07875"),"Sapezal", new Integer("51")));
        lista.add(new Municipio(new Integer("07883"),"Serra Nova Dourada", new Integer("51")));
        lista.add(new Municipio(new Integer("07909"),"Sinop", new Integer("51")));
        lista.add(new Municipio(new Integer("07925"),"Sorriso", new Integer("51")));
        lista.add(new Municipio(new Integer("07941"),"Tabaporã", new Integer("51")));
        lista.add(new Municipio(new Integer("07958"),"Tangará da Serra", new Integer("51")));
        lista.add(new Municipio(new Integer("08006"),"Tapurah", new Integer("51")));
        lista.add(new Municipio(new Integer("08055"),"Terra Nova do Norte", new Integer("51")));
        lista.add(new Municipio(new Integer("08105"),"Tesouro", new Integer("51")));
        lista.add(new Municipio(new Integer("08204"),"Torixoréu", new Integer("51")));
        lista.add(new Municipio(new Integer("08303"),"União do Sul", new Integer("51")));
        lista.add(new Municipio(new Integer("08352"),"Vale de São Domingos", new Integer("51")));
        lista.add(new Municipio(new Integer("08402"),"Várzea Grande", new Integer("51")));
        lista.add(new Municipio(new Integer("08501"),"Vera", new Integer("51")));
        lista.add(new Municipio(new Integer("08600"),"Vila Rica", new Integer("51")));
        lista.add(new Municipio(new Integer("08808"),"Nova Guarita", new Integer("51")));
        lista.add(new Municipio(new Integer("08857"),"Nova Marilândia", new Integer("51")));
        lista.add(new Municipio(new Integer("08907"),"Nova Maringá", new Integer("51")));
        lista.add(new Municipio(new Integer("08956"),"Nova Monte Verde", new Integer("51")));

        lista.add(new Municipio(new Integer("00050"),"Abadia de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("00100"),"Abadiânia", new Integer("52")));
        lista.add(new Municipio(new Integer("00134"),"Acreúna", new Integer("52")));
        lista.add(new Municipio(new Integer("00159"),"Adelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("00175"),"Água Fria de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("00209"),"Água Limpa", new Integer("52")));
        lista.add(new Municipio(new Integer("00258"),"Águas Lindas de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("00308"),"Alexânia", new Integer("52")));
        lista.add(new Municipio(new Integer("00506"),"Aloândia", new Integer("52")));
        lista.add(new Municipio(new Integer("00555"),"Alto Horizonte", new Integer("52")));
        lista.add(new Municipio(new Integer("00605"),"Alto Paraíso de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("00803"),"Alvorada do Norte", new Integer("52")));
        lista.add(new Municipio(new Integer("00829"),"Amaralina", new Integer("52")));
        lista.add(new Municipio(new Integer("00852"),"Americano do Brasil", new Integer("52")));
        lista.add(new Municipio(new Integer("00902"),"Amorinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("01108"),"Anápolis", new Integer("52")));
        lista.add(new Municipio(new Integer("01207"),"Anhanguera", new Integer("52")));
        lista.add(new Municipio(new Integer("01306"),"Anicuns", new Integer("52")));
        lista.add(new Municipio(new Integer("01405"),"Aparecida de Goiânia", new Integer("52")));
        lista.add(new Municipio(new Integer("01454"),"Aparecida do Rio Doce", new Integer("52")));
        lista.add(new Municipio(new Integer("01504"),"Aporé", new Integer("52")));
        lista.add(new Municipio(new Integer("01603"),"Araçu", new Integer("52")));
        lista.add(new Municipio(new Integer("01702"),"Aragarças", new Integer("52")));
        lista.add(new Municipio(new Integer("01801"),"Aragoiânia", new Integer("52")));
        lista.add(new Municipio(new Integer("02155"),"Araguapaz", new Integer("52")));
        lista.add(new Municipio(new Integer("02353"),"Arenópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("02502"),"Aruanã", new Integer("52")));
        lista.add(new Municipio(new Integer("02601"),"Aurilândia", new Integer("52")));
        lista.add(new Municipio(new Integer("02809"),"Avelinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("03104"),"Baliza", new Integer("52")));
        lista.add(new Municipio(new Integer("03203"),"Barro Alto", new Integer("52")));
        lista.add(new Municipio(new Integer("03302"),"Bela Vista de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("03401"),"Bom Jardim de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("03500"),"Bom Jesus de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("03559"),"Bonfinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("03575"),"Bonópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("03609"),"Brazabrantes", new Integer("52")));
        lista.add(new Municipio(new Integer("03807"),"Britânia", new Integer("52")));
        lista.add(new Municipio(new Integer("03906"),"Buriti Alegre", new Integer("52")));
        lista.add(new Municipio(new Integer("03939"),"Buriti de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("03962"),"Buritinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("04003"),"Cabeceiras", new Integer("52")));
        lista.add(new Municipio(new Integer("04102"),"Cachoeira Alta", new Integer("52")));
        lista.add(new Municipio(new Integer("04201"),"Cachoeira de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("04250"),"Cachoeira Dourada", new Integer("52")));
        lista.add(new Municipio(new Integer("04300"),"Caçu", new Integer("52")));
        lista.add(new Municipio(new Integer("04409"),"Caiapônia", new Integer("52")));
        lista.add(new Municipio(new Integer("04508"),"Caldas Novas", new Integer("52")));
        lista.add(new Municipio(new Integer("04557"),"Caldazinha", new Integer("52")));
        lista.add(new Municipio(new Integer("04607"),"Campestre de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("04656"),"Campinaçu", new Integer("52")));
        lista.add(new Municipio(new Integer("04706"),"Campinorte", new Integer("52")));
        lista.add(new Municipio(new Integer("04805"),"Campo Alegre de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("04854"),"Campo Limpo de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("04904"),"Campos Belos", new Integer("52")));
        lista.add(new Municipio(new Integer("04953"),"Campos Verdes", new Integer("52")));
        lista.add(new Municipio(new Integer("05000"),"Carmo do Rio Verde", new Integer("52")));
        lista.add(new Municipio(new Integer("05059"),"Castelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("05109"),"Catalão", new Integer("52")));
        lista.add(new Municipio(new Integer("05208"),"Caturaí", new Integer("52")));
        lista.add(new Municipio(new Integer("05307"),"Cavalcante", new Integer("52")));
        lista.add(new Municipio(new Integer("05406"),"Ceres", new Integer("52")));
        lista.add(new Municipio(new Integer("05455"),"Cezarina", new Integer("52")));
        lista.add(new Municipio(new Integer("05471"),"Chapadão do Céu", new Integer("52")));
        lista.add(new Municipio(new Integer("05497"),"Cidade Ocidental", new Integer("52")));
        lista.add(new Municipio(new Integer("05513"),"Cocalzinho de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("05521"),"Colinas do Sul", new Integer("52")));
        lista.add(new Municipio(new Integer("05703"),"Córrego do Ouro", new Integer("52")));
        lista.add(new Municipio(new Integer("05802"),"Corumbá de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("05901"),"Corumbaíba", new Integer("52")));
        lista.add(new Municipio(new Integer("06206"),"Cristalina", new Integer("52")));
        lista.add(new Municipio(new Integer("06305"),"Cristianópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("06404"),"Crixás", new Integer("52")));
        lista.add(new Municipio(new Integer("06503"),"Cromínia", new Integer("52")));
        lista.add(new Municipio(new Integer("06602"),"Cumari", new Integer("52")));
        lista.add(new Municipio(new Integer("06701"),"Damianópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("06800"),"Damolândia", new Integer("52")));
        lista.add(new Municipio(new Integer("06909"),"Davinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("07105"),"Diorama", new Integer("52")));
        lista.add(new Municipio(new Integer("07253"),"Doverlândia", new Integer("52")));
        lista.add(new Municipio(new Integer("07352"),"Edealina", new Integer("52")));
        lista.add(new Municipio(new Integer("07402"),"Edéia", new Integer("52")));
        lista.add(new Municipio(new Integer("07501"),"Estrela do Norte", new Integer("52")));
        lista.add(new Municipio(new Integer("07535"),"Faina", new Integer("52")));
        lista.add(new Municipio(new Integer("07600"),"Fazenda Nova", new Integer("52")));
        lista.add(new Municipio(new Integer("07808"),"Firminópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("07907"),"Flores de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("08004"),"Formosa", new Integer("52")));
        lista.add(new Municipio(new Integer("08103"),"Formoso", new Integer("52")));
        lista.add(new Municipio(new Integer("08152"),"Gameleira de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("08301"),"Divinópolis de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("08400"),"Goianápolis", new Integer("52")));
        lista.add(new Municipio(new Integer("08509"),"Goiandira", new Integer("52")));
        lista.add(new Municipio(new Integer("08608"),"Goianésia", new Integer("52")));
        lista.add(new Municipio(new Integer("08707"),"Goiânia", new Integer("52")));
        lista.add(new Municipio(new Integer("08806"),"Goianira", new Integer("52")));
        lista.add(new Municipio(new Integer("08905"),"Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("09101"),"Goiatuba", new Integer("52")));
        lista.add(new Municipio(new Integer("09150"),"Gouvelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("09200"),"Guapó", new Integer("52")));
        lista.add(new Municipio(new Integer("09291"),"Guaraíta", new Integer("52")));
        lista.add(new Municipio(new Integer("09408"),"Guarani de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("09457"),"Guarinos", new Integer("52")));
        lista.add(new Municipio(new Integer("09606"),"Heitoraí", new Integer("52")));
        lista.add(new Municipio(new Integer("09705"),"Hidrolândia", new Integer("52")));
        lista.add(new Municipio(new Integer("09804"),"Hidrolina", new Integer("52")));
        lista.add(new Municipio(new Integer("09903"),"Iaciara", new Integer("52")));
        lista.add(new Municipio(new Integer("09937"),"Inaciolândia", new Integer("52")));
        lista.add(new Municipio(new Integer("09952"),"Indiara", new Integer("52")));
        lista.add(new Municipio(new Integer("10000"),"Inhumas", new Integer("52")));
        lista.add(new Municipio(new Integer("10109"),"Ipameri", new Integer("52")));
        lista.add(new Municipio(new Integer("10158"),"Ipiranga de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("10208"),"Iporá", new Integer("52")));
        lista.add(new Municipio(new Integer("10307"),"Israelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("10406"),"Itaberaí", new Integer("52")));
        lista.add(new Municipio(new Integer("10562"),"Itaguari", new Integer("52")));
        lista.add(new Municipio(new Integer("10604"),"Itaguaru", new Integer("52")));
        lista.add(new Municipio(new Integer("10802"),"Itajá", new Integer("52")));
        lista.add(new Municipio(new Integer("10901"),"Itapaci", new Integer("52")));
        lista.add(new Municipio(new Integer("11008"),"Itapirapuã", new Integer("52")));
        lista.add(new Municipio(new Integer("11206"),"Itapuranga", new Integer("52")));
        lista.add(new Municipio(new Integer("11305"),"Itarumã", new Integer("52")));
        lista.add(new Municipio(new Integer("11404"),"Itauçu", new Integer("52")));
        lista.add(new Municipio(new Integer("11503"),"Itumbiara", new Integer("52")));
        lista.add(new Municipio(new Integer("11602"),"Ivolândia", new Integer("52")));
        lista.add(new Municipio(new Integer("11701"),"Jandaia", new Integer("52")));
        lista.add(new Municipio(new Integer("11800"),"Jaraguá", new Integer("52")));
        lista.add(new Municipio(new Integer("11909"),"Jataí", new Integer("52")));
        lista.add(new Municipio(new Integer("12006"),"Jaupaci", new Integer("52")));
        lista.add(new Municipio(new Integer("12055"),"Jesúpolis", new Integer("52")));
        lista.add(new Municipio(new Integer("12105"),"Joviânia", new Integer("52")));
        lista.add(new Municipio(new Integer("12204"),"Jussara", new Integer("52")));
        lista.add(new Municipio(new Integer("12253"),"Lagoa Santa", new Integer("52")));
        lista.add(new Municipio(new Integer("12303"),"Leopoldo de Bulhões", new Integer("52")));
        lista.add(new Municipio(new Integer("12501"),"Luziânia", new Integer("52")));
        lista.add(new Municipio(new Integer("12600"),"Mairipotaba", new Integer("52")));
        lista.add(new Municipio(new Integer("12709"),"Mambaí", new Integer("52")));
        lista.add(new Municipio(new Integer("12808"),"Mara Rosa", new Integer("52")));
        lista.add(new Municipio(new Integer("12907"),"Marzagão", new Integer("52")));
        lista.add(new Municipio(new Integer("12956"),"Matrinchã", new Integer("52")));
        lista.add(new Municipio(new Integer("13004"),"Maurilândia", new Integer("52")));
        lista.add(new Municipio(new Integer("13053"),"Mimoso de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("13087"),"Minaçu", new Integer("52")));
        lista.add(new Municipio(new Integer("13103"),"Mineiros", new Integer("52")));
        lista.add(new Municipio(new Integer("13400"),"Moiporá", new Integer("52")));
        lista.add(new Municipio(new Integer("13509"),"Monte Alegre de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("13707"),"Montes Claros de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("13756"),"Montividiu", new Integer("52")));
        lista.add(new Municipio(new Integer("13772"),"Montividiu do Norte", new Integer("52")));
        lista.add(new Municipio(new Integer("13806"),"Morrinhos", new Integer("52")));
        lista.add(new Municipio(new Integer("13855"),"Morro Agudo de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("13905"),"Mossâmedes", new Integer("52")));
        lista.add(new Municipio(new Integer("14002"),"Mozarlândia", new Integer("52")));
        lista.add(new Municipio(new Integer("14051"),"Mundo Novo", new Integer("52")));
        lista.add(new Municipio(new Integer("14101"),"Mutunópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("14408"),"Nazário", new Integer("52")));
        lista.add(new Municipio(new Integer("14507"),"Nerópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("14606"),"Niquelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("14705"),"Nova América", new Integer("52")));
        lista.add(new Municipio(new Integer("14804"),"Nova Aurora", new Integer("52")));
        lista.add(new Municipio(new Integer("14838"),"Nova Crixás", new Integer("52")));
        lista.add(new Municipio(new Integer("14861"),"Nova Glória", new Integer("52")));
        lista.add(new Municipio(new Integer("14879"),"Nova Iguaçu de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("14903"),"Nova Roma", new Integer("52")));
        lista.add(new Municipio(new Integer("15009"),"Nova Veneza", new Integer("52")));
        lista.add(new Municipio(new Integer("15207"),"Novo Brasil", new Integer("52")));
        lista.add(new Municipio(new Integer("15231"),"Novo Gama", new Integer("52")));
        lista.add(new Municipio(new Integer("15256"),"Novo Planalto", new Integer("52")));
        lista.add(new Municipio(new Integer("15306"),"Orizona", new Integer("52")));
        lista.add(new Municipio(new Integer("15405"),"Ouro Verde de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("15504"),"Ouvidor", new Integer("52")));
        lista.add(new Municipio(new Integer("15603"),"Padre Bernardo", new Integer("52")));
        lista.add(new Municipio(new Integer("15652"),"Palestina de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("15702"),"Palmeiras de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("15801"),"Palmelo", new Integer("52")));
        lista.add(new Municipio(new Integer("15900"),"Palminópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("16007"),"Panamá", new Integer("52")));
        lista.add(new Municipio(new Integer("16304"),"Paranaiguara", new Integer("52")));
        lista.add(new Municipio(new Integer("16403"),"Paraúna", new Integer("52")));
        lista.add(new Municipio(new Integer("16452"),"Perolândia", new Integer("52")));
        lista.add(new Municipio(new Integer("16809"),"Petrolina de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("16908"),"Pilar de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("17104"),"Piracanjuba", new Integer("52")));
        lista.add(new Municipio(new Integer("17203"),"Piranhas", new Integer("52")));
        lista.add(new Municipio(new Integer("17302"),"Pirenópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("17401"),"Pires do Rio", new Integer("52")));
        lista.add(new Municipio(new Integer("17609"),"Planaltina", new Integer("52")));
        lista.add(new Municipio(new Integer("17708"),"Pontalina", new Integer("52")));
        lista.add(new Municipio(new Integer("18003"),"Porangatu", new Integer("52")));
        lista.add(new Municipio(new Integer("18052"),"Porteirão", new Integer("52")));
        lista.add(new Municipio(new Integer("18102"),"Portelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("18300"),"Posse", new Integer("52")));
        lista.add(new Municipio(new Integer("18391"),"Professor Jamil", new Integer("52")));
        lista.add(new Municipio(new Integer("18508"),"Quirinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("18607"),"Rialma", new Integer("52")));
        lista.add(new Municipio(new Integer("18706"),"Rianápolis", new Integer("52")));
        lista.add(new Municipio(new Integer("18789"),"Rio Quente", new Integer("52")));
        lista.add(new Municipio(new Integer("18805"),"Rio Verde", new Integer("52")));
        lista.add(new Municipio(new Integer("18904"),"Rubiataba", new Integer("52")));
        lista.add(new Municipio(new Integer("19001"),"Sanclerlândia", new Integer("52")));
        lista.add(new Municipio(new Integer("19100"),"Santa Bárbara de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19209"),"Santa Cruz de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19258"),"Santa Fé de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19308"),"Santa Helena de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19357"),"Santa Isabel", new Integer("52")));
        lista.add(new Municipio(new Integer("19407"),"Santa Rita do Araguaia", new Integer("52")));
        lista.add(new Municipio(new Integer("19456"),"Santa Rita do Novo Destino", new Integer("52")));
        lista.add(new Municipio(new Integer("19506"),"Santa Rosa de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19605"),"Santa Tereza de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19704"),"Santa Terezinha de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19712"),"Santo Antônio da Barra", new Integer("52")));
        lista.add(new Municipio(new Integer("19738"),"Santo Antônio de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("19753"),"Santo Antônio do Descoberto", new Integer("52")));
        lista.add(new Municipio(new Integer("19803"),"São Domingos", new Integer("52")));
        lista.add(new Municipio(new Integer("19902"),"São Francisco de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("20009"),"São João d'Aliança", new Integer("52")));
        lista.add(new Municipio(new Integer("20058"),"São João da Paraúna", new Integer("52")));
        lista.add(new Municipio(new Integer("20108"),"São Luís de Montes Belos", new Integer("52")));
        lista.add(new Municipio(new Integer("20157"),"São Luíz do Norte", new Integer("52")));
        lista.add(new Municipio(new Integer("20207"),"São Miguel do Araguaia", new Integer("52")));
        lista.add(new Municipio(new Integer("20264"),"São Miguel do Passa Quatro", new Integer("52")));
        lista.add(new Municipio(new Integer("20280"),"São Patrício", new Integer("52")));
        lista.add(new Municipio(new Integer("20405"),"São Simão", new Integer("52")));
        lista.add(new Municipio(new Integer("20454"),"Senador Canedo", new Integer("52")));
        lista.add(new Municipio(new Integer("20504"),"Serranópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("20603"),"Silvânia", new Integer("52")));
        lista.add(new Municipio(new Integer("20686"),"Simolândia", new Integer("52")));
        lista.add(new Municipio(new Integer("20702"),"Sítio d'Abadia", new Integer("52")));
        lista.add(new Municipio(new Integer("21007"),"Taquaral de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("21080"),"Teresina de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("21197"),"Terezópolis de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("21304"),"Três Ranchos", new Integer("52")));
        lista.add(new Municipio(new Integer("21403"),"Trindade", new Integer("52")));
        lista.add(new Municipio(new Integer("21452"),"Trombas", new Integer("52")));
        lista.add(new Municipio(new Integer("21502"),"Turvânia", new Integer("52")));
        lista.add(new Municipio(new Integer("21551"),"Turvelândia", new Integer("52")));
        lista.add(new Municipio(new Integer("21577"),"Uirapuru", new Integer("52")));
        lista.add(new Municipio(new Integer("21601"),"Uruaçu", new Integer("52")));
        lista.add(new Municipio(new Integer("21700"),"Uruana", new Integer("52")));
        lista.add(new Municipio(new Integer("21809"),"Urutaí", new Integer("52")));
        lista.add(new Municipio(new Integer("21858"),"Valparaíso de Goiás", new Integer("52")));
        lista.add(new Municipio(new Integer("21908"),"Varjão", new Integer("52")));
        lista.add(new Municipio(new Integer("22005"),"Vianópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("22054"),"Vicentinópolis", new Integer("52")));
        lista.add(new Municipio(new Integer("22203"),"Vila Boa", new Integer("52")));
        lista.add(new Municipio(new Integer("22302"),"Vila Propício", new Integer("52")));

        lista.add(new Municipio(new Integer("00108"),"Brasília", new Integer("53")));

        Collections.sort(lista);
        return lista;
    }
}
