package br.com.adem.iconv.dao;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import br.com.adem.iconv.model.Municipio;

/**
 * Created by eduardo on 28/03/2016.
 */
public class MunicipioDAO {
    
    private List<Municipio> listar() {
        List<Municipio> lista = new ArrayList<Municipio>();

        lista.add(new Municipio(new Integer("00015"),"Alta Floresta D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00023"),"Ariquemes", new Integer("11")));
        lista.add(new Municipio(new Integer("00031"),"Cabixi", new Integer("11")));
        lista.add(new Municipio(new Integer("00049"),"Cacoal", new Integer("11")));
        lista.add(new Municipio(new Integer("00056"),"Cerejeiras", new Integer("11")));
        lista.add(new Municipio(new Integer("00064"),"Colorado do Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00072"),"Corumbiara", new Integer("11")));
        lista.add(new Municipio(new Integer("00080"),"Costa Marques", new Integer("11")));
        lista.add(new Municipio(new Integer("00098"),"Espigão D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00106"),"Guajará-Mirim", new Integer("11")));
        lista.add(new Municipio(new Integer("00114"),"Jaru", new Integer("11")));
        lista.add(new Municipio(new Integer("00122"),"Ji-Paraná", new Integer("11")));
        lista.add(new Municipio(new Integer("00130"),"Machadinho D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00148"),"Nova Brasilândia D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00155"),"Ouro Preto do Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00189"),"Pimenta Bueno", new Integer("11")));
        lista.add(new Municipio(new Integer("00205"),"Porto Velho", new Integer("11")));
        lista.add(new Municipio(new Integer("00254"),"Presidente Médici", new Integer("11")));
        lista.add(new Municipio(new Integer("00262"),"Rio Crespo", new Integer("11")));
        lista.add(new Municipio(new Integer("00288"),"Rolim de Moura", new Integer("11")));
        lista.add(new Municipio(new Integer("00296"),"Santa Luzia D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00304"),"Vilhena", new Integer("11")));
        lista.add(new Municipio(new Integer("00320"),"São Miguel do Guaporé", new Integer("11")));
        lista.add(new Municipio(new Integer("00338"),"Nova Mamoré", new Integer("11")));
        lista.add(new Municipio(new Integer("00346"),"Alvorada D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00379"),"Alto Alegre dos Parecis", new Integer("11")));
        lista.add(new Municipio(new Integer("00403"),"Alto Paraíso", new Integer("11")));
        lista.add(new Municipio(new Integer("00452"),"Buritis", new Integer("11")));
        lista.add(new Municipio(new Integer("00502"),"Novo Horizonte do Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("00601"),"Cacaulândia", new Integer("11")));
        lista.add(new Municipio(new Integer("00700"),"Campo Novo de Rondônia", new Integer("11")));
        lista.add(new Municipio(new Integer("00809"),"Candeias do Jamari", new Integer("11")));
        lista.add(new Municipio(new Integer("00908"),"Castanheiras", new Integer("11")));
        lista.add(new Municipio(new Integer("00924"),"Chupinguaia", new Integer("11")));
        lista.add(new Municipio(new Integer("00940"),"Cujubim", new Integer("11")));
        lista.add(new Municipio(new Integer("01005"),"Governador Jorge Teixeira", new Integer("11")));
        lista.add(new Municipio(new Integer("01104"),"Itapuã do Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("01203"),"Ministro Andreazza", new Integer("11")));
        lista.add(new Municipio(new Integer("01302"),"Mirante da Serra", new Integer("11")));
        lista.add(new Municipio(new Integer("01401"),"Monte Negro", new Integer("11")));
        lista.add(new Municipio(new Integer("01435"),"Nova União", new Integer("11")));
        lista.add(new Municipio(new Integer("01450"),"Parecis", new Integer("11")));
        lista.add(new Municipio(new Integer("01468"),"Pimenteiras do Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("01476"),"Primavera de Rondônia", new Integer("11")));
        lista.add(new Municipio(new Integer("01484"),"São Felipe D'Oeste", new Integer("11")));
        lista.add(new Municipio(new Integer("01492"),"São Francisco do Guaporé", new Integer("11")));
        lista.add(new Municipio(new Integer("01500"),"Seringueiras", new Integer("11")));
        lista.add(new Municipio(new Integer("01559"),"Teixeirópolis", new Integer("11")));
        lista.add(new Municipio(new Integer("01609"),"Theobroma", new Integer("11")));
        lista.add(new Municipio(new Integer("01708"),"Urupá", new Integer("11")));
        lista.add(new Municipio(new Integer("01757"),"Vale do Anari", new Integer("11")));
        lista.add(new Municipio(new Integer("01807"),"Vale do Paraíso", new Integer("11")));
        lista.add(new Municipio(new Integer("00013"),"Acrelândia", new Integer("12")));
        lista.add(new Municipio(new Integer("00054"),"Assis Brasil", new Integer("12")));
        lista.add(new Municipio(new Integer("00104"),"Brasiléia", new Integer("12")));
        lista.add(new Municipio(new Integer("00138"),"Bujari", new Integer("12")));
        lista.add(new Municipio(new Integer("00179"),"Capixaba", new Integer("12")));
        lista.add(new Municipio(new Integer("00203"),"Cruzeiro do Sul", new Integer("12")));
        lista.add(new Municipio(new Integer("00252"),"Epitaciolândia", new Integer("12")));
        lista.add(new Municipio(new Integer("00302"),"Feijó", new Integer("12")));
        lista.add(new Municipio(new Integer("00328"),"Jordão", new Integer("12")));
        lista.add(new Municipio(new Integer("00336"),"Mâncio Lima", new Integer("12")));
        lista.add(new Municipio(new Integer("00344"),"Manoel Urbano", new Integer("12")));
        lista.add(new Municipio(new Integer("00351"),"Marechal Thaumaturgo", new Integer("12")));
        lista.add(new Municipio(new Integer("00385"),"Plácido de Castro", new Integer("12")));
        lista.add(new Municipio(new Integer("00393"),"Porto Walter", new Integer("12")));
        lista.add(new Municipio(new Integer("00401"),"Rio Branco", new Integer("12")));
        lista.add(new Municipio(new Integer("00427"),"Rodrigues Alves", new Integer("12")));
        lista.add(new Municipio(new Integer("00435"),"Santa Rosa do Purus", new Integer("12")));
        lista.add(new Municipio(new Integer("00450"),"Senador Guiomard", new Integer("12")));
        lista.add(new Municipio(new Integer("00500"),"Sena Madureira", new Integer("12")));
        lista.add(new Municipio(new Integer("00609"),"Tarauacá", new Integer("12")));
        lista.add(new Municipio(new Integer("00708"),"Xapuri", new Integer("12")));
        lista.add(new Municipio(new Integer("00807"),"Porto Acre", new Integer("12")));
        lista.add(new Municipio(new Integer("00029"),"Alvarães", new Integer("13")));
        lista.add(new Municipio(new Integer("00060"),"Amaturá", new Integer("13")));
        lista.add(new Municipio(new Integer("00086"),"Anamã", new Integer("13")));
        lista.add(new Municipio(new Integer("00102"),"Anori", new Integer("13")));
        lista.add(new Municipio(new Integer("00144"),"Apuí", new Integer("13")));
        lista.add(new Municipio(new Integer("00201"),"Atalaia do Norte", new Integer("13")));
        lista.add(new Municipio(new Integer("00300"),"Autazes", new Integer("13")));
        lista.add(new Municipio(new Integer("00409"),"Barcelos", new Integer("13")));
        lista.add(new Municipio(new Integer("00508"),"Barreirinha", new Integer("13")));
        lista.add(new Municipio(new Integer("00607"),"Benjamin Constant", new Integer("13")));
        lista.add(new Municipio(new Integer("00631"),"Beruri", new Integer("13")));
        lista.add(new Municipio(new Integer("00680"),"Boa Vista do Ramos", new Integer("13")));
        lista.add(new Municipio(new Integer("00706"),"Boca do Acre", new Integer("13")));
        lista.add(new Municipio(new Integer("00805"),"Borba", new Integer("13")));
        lista.add(new Municipio(new Integer("00839"),"Caapiranga", new Integer("13")));
        lista.add(new Municipio(new Integer("00904"),"Canutama", new Integer("13")));
        lista.add(new Municipio(new Integer("01001"),"Carauari", new Integer("13")));
        lista.add(new Municipio(new Integer("01100"),"Careiro", new Integer("13")));
        lista.add(new Municipio(new Integer("01159"),"Careiro da Várzea", new Integer("13")));
        lista.add(new Municipio(new Integer("01209"),"Coari", new Integer("13")));
        lista.add(new Municipio(new Integer("01308"),"Codajás", new Integer("13")));
        lista.add(new Municipio(new Integer("01407"),"Eirunepé", new Integer("13")));
        lista.add(new Municipio(new Integer("01506"),"Envira", new Integer("13")));
        lista.add(new Municipio(new Integer("01605"),"Fonte Boa", new Integer("13")));
        lista.add(new Municipio(new Integer("01654"),"Guajará", new Integer("13")));
        lista.add(new Municipio(new Integer("01704"),"Humaitá", new Integer("13")));
        lista.add(new Municipio(new Integer("01803"),"Ipixuna", new Integer("13")));
        lista.add(new Municipio(new Integer("01852"),"Iranduba", new Integer("13")));
        lista.add(new Municipio(new Integer("01902"),"Itacoatiara", new Integer("13")));
        lista.add(new Municipio(new Integer("01951"),"Itamarati", new Integer("13")));
        lista.add(new Municipio(new Integer("02009"),"Itapiranga", new Integer("13")));
        lista.add(new Municipio(new Integer("02108"),"Japurá", new Integer("13")));
        lista.add(new Municipio(new Integer("02207"),"Juruá", new Integer("13")));
        lista.add(new Municipio(new Integer("02306"),"Jutaí", new Integer("13")));
        lista.add(new Municipio(new Integer("02405"),"Lábrea", new Integer("13")));
        lista.add(new Municipio(new Integer("02504"),"Manacapuru", new Integer("13")));
        lista.add(new Municipio(new Integer("02553"),"Manaquiri", new Integer("13")));
        lista.add(new Municipio(new Integer("02603"),"Manaus", new Integer("13")));
        lista.add(new Municipio(new Integer("02702"),"Manicoré", new Integer("13")));
        lista.add(new Municipio(new Integer("02801"),"Maraã", new Integer("13")));
        lista.add(new Municipio(new Integer("02900"),"Maués", new Integer("13")));
        lista.add(new Municipio(new Integer("03007"),"Nhamundá", new Integer("13")));
        lista.add(new Municipio(new Integer("03106"),"Nova Olinda do Norte", new Integer("13")));
        lista.add(new Municipio(new Integer("03205"),"Novo Airão", new Integer("13")));
        lista.add(new Municipio(new Integer("03304"),"Novo Aripuanã", new Integer("13")));
        lista.add(new Municipio(new Integer("03403"),"Parintins", new Integer("13")));
        lista.add(new Municipio(new Integer("03502"),"Pauini", new Integer("13")));
        lista.add(new Municipio(new Integer("03536"),"Presidente Figueiredo", new Integer("13")));
        lista.add(new Municipio(new Integer("03569"),"Rio Preto da Eva", new Integer("13")));
        lista.add(new Municipio(new Integer("03601"),"Santa Isabel do Rio Negro", new Integer("13")));
        lista.add(new Municipio(new Integer("03700"),"Santo Antônio do Içá", new Integer("13")));
        lista.add(new Municipio(new Integer("03809"),"São Gabriel da Cachoeira", new Integer("13")));
        lista.add(new Municipio(new Integer("03908"),"São Paulo de Olivença", new Integer("13")));
        lista.add(new Municipio(new Integer("03957"),"São Sebastião do Uatumã", new Integer("13")));
        lista.add(new Municipio(new Integer("04005"),"Silves", new Integer("13")));
        lista.add(new Municipio(new Integer("04062"),"Tabatinga", new Integer("13")));
        lista.add(new Municipio(new Integer("04104"),"Tapauá", new Integer("13")));
        lista.add(new Municipio(new Integer("04203"),"Tefé", new Integer("13")));
        lista.add(new Municipio(new Integer("04237"),"Tonantins", new Integer("13")));
        lista.add(new Municipio(new Integer("04260"),"Uarini", new Integer("13")));
        lista.add(new Municipio(new Integer("04302"),"Urucará", new Integer("13")));
        lista.add(new Municipio(new Integer("04401"),"Urucurituba", new Integer("13")));
        lista.add(new Municipio(new Integer("00027"),"Amajari", new Integer("14")));
        lista.add(new Municipio(new Integer("00050"),"Alto Alegre", new Integer("14")));
        lista.add(new Municipio(new Integer("00100"),"Boa Vista", new Integer("14")));
        lista.add(new Municipio(new Integer("00159"),"Bonfim", new Integer("14")));
        lista.add(new Municipio(new Integer("00175"),"Cantá", new Integer("14")));
        lista.add(new Municipio(new Integer("00209"),"Caracaraí", new Integer("14")));
        lista.add(new Municipio(new Integer("00233"),"Caroebe", new Integer("14")));
        lista.add(new Municipio(new Integer("00282"),"Iracema", new Integer("14")));
        lista.add(new Municipio(new Integer("00308"),"Mucajaí", new Integer("14")));
        lista.add(new Municipio(new Integer("00407"),"Normandia", new Integer("14")));
        lista.add(new Municipio(new Integer("00456"),"Pacaraima", new Integer("14")));
        lista.add(new Municipio(new Integer("00472"),"Rorainópolis", new Integer("14")));
        lista.add(new Municipio(new Integer("00506"),"São João da Baliza", new Integer("14")));
        lista.add(new Municipio(new Integer("00605"),"São Luiz", new Integer("14")));
        lista.add(new Municipio(new Integer("00704"),"Uiramutã", new Integer("14")));
        lista.add(new Municipio(new Integer("00107"),"Abaetetuba", new Integer("15")));
        lista.add(new Municipio(new Integer("00131"),"Abel Figueiredo", new Integer("15")));
        lista.add(new Municipio(new Integer("00206"),"Acará", new Integer("15")));
        lista.add(new Municipio(new Integer("00305"),"Afuá", new Integer("15")));
        lista.add(new Municipio(new Integer("00347"),"Água Azul do Norte", new Integer("15")));
        lista.add(new Municipio(new Integer("00404"),"Alenquer", new Integer("15")));
        lista.add(new Municipio(new Integer("00503"),"Almeirim", new Integer("15")));
        lista.add(new Municipio(new Integer("00602"),"Altamira", new Integer("15")));
        lista.add(new Municipio(new Integer("00701"),"Anajás", new Integer("15")));
        lista.add(new Municipio(new Integer("00800"),"Ananindeua", new Integer("15")));
        lista.add(new Municipio(new Integer("00859"),"Anapu", new Integer("15")));
        lista.add(new Municipio(new Integer("00909"),"Augusto Corrêa", new Integer("15")));
        lista.add(new Municipio(new Integer("00958"),"Aurora do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("01006"),"Aveiro", new Integer("15")));
        lista.add(new Municipio(new Integer("01105"),"Bagre", new Integer("15")));
        lista.add(new Municipio(new Integer("01204"),"Baião", new Integer("15")));
        lista.add(new Municipio(new Integer("01253"),"Bannach", new Integer("15")));
        lista.add(new Municipio(new Integer("01303"),"Barcarena", new Integer("15")));
        lista.add(new Municipio(new Integer("01402"),"Belém", new Integer("15")));
        lista.add(new Municipio(new Integer("01451"),"Belterra", new Integer("15")));
        lista.add(new Municipio(new Integer("01501"),"Benevides", new Integer("15")));
        lista.add(new Municipio(new Integer("01576"),"Bom Jesus do Tocantins", new Integer("15")));
        lista.add(new Municipio(new Integer("01600"),"Bonito", new Integer("15")));
        lista.add(new Municipio(new Integer("01709"),"Bragança", new Integer("15")));
        lista.add(new Municipio(new Integer("01725"),"Brasil Novo", new Integer("15")));
        lista.add(new Municipio(new Integer("01758"),"Brejo Grande do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("01782"),"Breu Branco", new Integer("15")));
        lista.add(new Municipio(new Integer("01808"),"Breves", new Integer("15")));
        lista.add(new Municipio(new Integer("01907"),"Bujaru", new Integer("15")));
        lista.add(new Municipio(new Integer("01956"),"Cachoeira do Piriá", new Integer("15")));
        lista.add(new Municipio(new Integer("02004"),"Cachoeira do Arari", new Integer("15")));
        lista.add(new Municipio(new Integer("02103"),"Cametá", new Integer("15")));
        lista.add(new Municipio(new Integer("02152"),"Canaã dos Carajás", new Integer("15")));
        lista.add(new Municipio(new Integer("02202"),"Capanema", new Integer("15")));
        lista.add(new Municipio(new Integer("02301"),"Capitão Poço", new Integer("15")));
        lista.add(new Municipio(new Integer("02400"),"Castanhal", new Integer("15")));
        lista.add(new Municipio(new Integer("02509"),"Chaves", new Integer("15")));
        lista.add(new Municipio(new Integer("02608"),"Colares", new Integer("15")));
        lista.add(new Municipio(new Integer("02707"),"Conceição do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("02756"),"Concórdia do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("02764"),"Cumaru do Norte", new Integer("15")));
        lista.add(new Municipio(new Integer("02772"),"Curionópolis", new Integer("15")));
        lista.add(new Municipio(new Integer("02806"),"Curralinho", new Integer("15")));
        lista.add(new Municipio(new Integer("02855"),"Curuá", new Integer("15")));
        lista.add(new Municipio(new Integer("02905"),"Curuçá", new Integer("15")));
        lista.add(new Municipio(new Integer("02939"),"Dom Eliseu", new Integer("15")));
        lista.add(new Municipio(new Integer("02954"),"Eldorado do Carajás", new Integer("15")));
        lista.add(new Municipio(new Integer("03002"),"Faro", new Integer("15")));
        lista.add(new Municipio(new Integer("03044"),"Floresta do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("03077"),"Garrafão do Norte", new Integer("15")));
        lista.add(new Municipio(new Integer("03093"),"Goianésia do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("03101"),"Gurupá", new Integer("15")));
        lista.add(new Municipio(new Integer("03200"),"Igarapé-Açu", new Integer("15")));
        lista.add(new Municipio(new Integer("03309"),"Igarapé-Miri", new Integer("15")));
        lista.add(new Municipio(new Integer("03408"),"Inhangapi", new Integer("15")));
        lista.add(new Municipio(new Integer("03457"),"Ipixuna do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("03507"),"Irituia", new Integer("15")));
        lista.add(new Municipio(new Integer("03606"),"Itaituba", new Integer("15")));
        lista.add(new Municipio(new Integer("03705"),"Itupiranga", new Integer("15")));
        lista.add(new Municipio(new Integer("03754"),"Jacareacanga", new Integer("15")));
        lista.add(new Municipio(new Integer("03804"),"Jacundá", new Integer("15")));
        lista.add(new Municipio(new Integer("03903"),"Juruti", new Integer("15")));
        lista.add(new Municipio(new Integer("04000"),"Limoeiro do Ajuru", new Integer("15")));
        lista.add(new Municipio(new Integer("04059"),"Mãe do Rio", new Integer("15")));
        lista.add(new Municipio(new Integer("04109"),"Magalhães Barata", new Integer("15")));
        lista.add(new Municipio(new Integer("04208"),"Marabá", new Integer("15")));
        lista.add(new Municipio(new Integer("04307"),"Maracanã", new Integer("15")));
        lista.add(new Municipio(new Integer("04406"),"Marapanim", new Integer("15")));
        lista.add(new Municipio(new Integer("04422"),"Marituba", new Integer("15")));
        lista.add(new Municipio(new Integer("04455"),"Medicilândia", new Integer("15")));
        lista.add(new Municipio(new Integer("04505"),"Melgaço", new Integer("15")));
        lista.add(new Municipio(new Integer("04604"),"Mocajuba", new Integer("15")));
        lista.add(new Municipio(new Integer("04703"),"Moju", new Integer("15")));
        lista.add(new Municipio(new Integer("04752"),"Mojuí dos Campos", new Integer("15")));
        lista.add(new Municipio(new Integer("04802"),"Monte Alegre", new Integer("15")));
        lista.add(new Municipio(new Integer("04901"),"Muaná", new Integer("15")));
        lista.add(new Municipio(new Integer("04950"),"Nova Esperança do Piriá", new Integer("15")));
        lista.add(new Municipio(new Integer("04976"),"Nova Ipixuna", new Integer("15")));
        lista.add(new Municipio(new Integer("05007"),"Nova Timboteua", new Integer("15")));
        lista.add(new Municipio(new Integer("05031"),"Novo Progresso", new Integer("15")));
        lista.add(new Municipio(new Integer("05064"),"Novo Repartimento", new Integer("15")));
        lista.add(new Municipio(new Integer("05106"),"Óbidos", new Integer("15")));
        lista.add(new Municipio(new Integer("05205"),"Oeiras do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("05304"),"Oriximiná", new Integer("15")));
        lista.add(new Municipio(new Integer("05403"),"Ourém", new Integer("15")));
        lista.add(new Municipio(new Integer("05437"),"Ourilândia do Norte", new Integer("15")));
        lista.add(new Municipio(new Integer("05486"),"Pacajá", new Integer("15")));
        lista.add(new Municipio(new Integer("05494"),"Palestina do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("05502"),"Paragominas", new Integer("15")));
        lista.add(new Municipio(new Integer("05536"),"Parauapebas", new Integer("15")));
        lista.add(new Municipio(new Integer("05551"),"Pau D'Arco", new Integer("15")));
        lista.add(new Municipio(new Integer("05601"),"Peixe-Boi", new Integer("15")));
        lista.add(new Municipio(new Integer("05635"),"Piçarra", new Integer("15")));
        lista.add(new Municipio(new Integer("05650"),"Placas", new Integer("15")));
        lista.add(new Municipio(new Integer("05700"),"Ponta de Pedras", new Integer("15")));
        lista.add(new Municipio(new Integer("05809"),"Portel", new Integer("15")));
        lista.add(new Municipio(new Integer("05908"),"Porto de Moz", new Integer("15")));
        lista.add(new Municipio(new Integer("06005"),"Prainha", new Integer("15")));
        lista.add(new Municipio(new Integer("06104"),"Primavera", new Integer("15")));
        lista.add(new Municipio(new Integer("06112"),"Quatipuru", new Integer("15")));
        lista.add(new Municipio(new Integer("06138"),"Redenção", new Integer("15")));
        lista.add(new Municipio(new Integer("06161"),"Rio Maria", new Integer("15")));
        lista.add(new Municipio(new Integer("06187"),"Rondon do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("06195"),"Rurópolis", new Integer("15")));
        lista.add(new Municipio(new Integer("06203"),"Salinópolis", new Integer("15")));
        lista.add(new Municipio(new Integer("06302"),"Salvaterra", new Integer("15")));
        lista.add(new Municipio(new Integer("06351"),"Santa Bárbara do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("06401"),"Santa Cruz do Arari", new Integer("15")));
        lista.add(new Municipio(new Integer("06500"),"Santa Izabel do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("06559"),"Santa Luzia do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("06583"),"Santa Maria das Barreiras", new Integer("15")));
        lista.add(new Municipio(new Integer("06609"),"Santa Maria do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("06708"),"Santana do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("06807"),"Santarém", new Integer("15")));
        lista.add(new Municipio(new Integer("06906"),"Santarém Novo", new Integer("15")));
        lista.add(new Municipio(new Integer("07003"),"Santo Antônio do Tauá", new Integer("15")));
        lista.add(new Municipio(new Integer("07102"),"São Caetano de Odivelas", new Integer("15")));
        lista.add(new Municipio(new Integer("07151"),"São Domingos do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("07201"),"São Domingos do Capim", new Integer("15")));
        lista.add(new Municipio(new Integer("07300"),"São Félix do Xingu", new Integer("15")));
        lista.add(new Municipio(new Integer("07409"),"São Francisco do Pará", new Integer("15")));
        lista.add(new Municipio(new Integer("07458"),"São Geraldo do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("07466"),"São João da Ponta", new Integer("15")));
        lista.add(new Municipio(new Integer("07474"),"São João de Pirabas", new Integer("15")));
        lista.add(new Municipio(new Integer("07508"),"São João do Araguaia", new Integer("15")));
        lista.add(new Municipio(new Integer("07607"),"São Miguel do Guamá", new Integer("15")));
        lista.add(new Municipio(new Integer("07706"),"São Sebastião da Boa Vista", new Integer("15")));
        lista.add(new Municipio(new Integer("07755"),"Sapucaia", new Integer("15")));
        lista.add(new Municipio(new Integer("07805"),"Senador José Porfírio", new Integer("15")));
        lista.add(new Municipio(new Integer("07904"),"Soure", new Integer("15")));
        lista.add(new Municipio(new Integer("07953"),"Tailândia", new Integer("15")));
        lista.add(new Municipio(new Integer("07961"),"Terra Alta", new Integer("15")));
        lista.add(new Municipio(new Integer("07979"),"Terra Santa", new Integer("15")));
        lista.add(new Municipio(new Integer("08001"),"Tomé-Açu", new Integer("15")));
        lista.add(new Municipio(new Integer("08035"),"Tracuateua", new Integer("15")));
        lista.add(new Municipio(new Integer("08050"),"Trairão", new Integer("15")));
        lista.add(new Municipio(new Integer("08084"),"Tucumã", new Integer("15")));
        lista.add(new Municipio(new Integer("08100"),"Tucuruí", new Integer("15")));
        lista.add(new Municipio(new Integer("08126"),"Ulianópolis", new Integer("15")));
        lista.add(new Municipio(new Integer("08159"),"Uruará", new Integer("15")));
        lista.add(new Municipio(new Integer("08209"),"Vigia", new Integer("15")));
        lista.add(new Municipio(new Integer("08308"),"Viseu", new Integer("15")));
        lista.add(new Municipio(new Integer("08357"),"Vitória do Xingu", new Integer("15")));
        lista.add(new Municipio(new Integer("08407"),"Xinguara", new Integer("15")));
        lista.add(new Municipio(new Integer("00055"),"Serra do Navio", new Integer("16")));
        lista.add(new Municipio(new Integer("00105"),"Amapá", new Integer("16")));
        lista.add(new Municipio(new Integer("00154"),"Pedra Branca do Amapari", new Integer("16")));
        lista.add(new Municipio(new Integer("00204"),"Calçoene", new Integer("16")));
        lista.add(new Municipio(new Integer("00212"),"Cutias", new Integer("16")));
        lista.add(new Municipio(new Integer("00238"),"Ferreira Gomes", new Integer("16")));
        lista.add(new Municipio(new Integer("00253"),"Itaubal", new Integer("16")));
        lista.add(new Municipio(new Integer("00279"),"Laranjal do Jari", new Integer("16")));
        lista.add(new Municipio(new Integer("00303"),"Macapá", new Integer("16")));
        lista.add(new Municipio(new Integer("00402"),"Mazagão", new Integer("16")));
        lista.add(new Municipio(new Integer("00501"),"Oiapoque", new Integer("16")));
        lista.add(new Municipio(new Integer("00535"),"Porto Grande", new Integer("16")));
        lista.add(new Municipio(new Integer("00550"),"Pracuúba", new Integer("16")));
        lista.add(new Municipio(new Integer("00600"),"Santana", new Integer("16")));
        lista.add(new Municipio(new Integer("00709"),"Tartarugalzinho", new Integer("16")));
        lista.add(new Municipio(new Integer("00808"),"Vitória do Jari", new Integer("16")));
        lista.add(new Municipio(new Integer("00251"),"Abreulândia", new Integer("17")));
        lista.add(new Municipio(new Integer("00301"),"Aguiarnópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("00350"),"Aliança do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("00400"),"Almas", new Integer("17")));
        lista.add(new Municipio(new Integer("00707"),"Alvorada", new Integer("17")));
        lista.add(new Municipio(new Integer("01002"),"Ananás", new Integer("17")));
        lista.add(new Municipio(new Integer("01051"),"Angico", new Integer("17")));
        lista.add(new Municipio(new Integer("01101"),"Aparecida do Rio Negro", new Integer("17")));
        lista.add(new Municipio(new Integer("01309"),"Aragominas", new Integer("17")));
        lista.add(new Municipio(new Integer("01903"),"Araguacema", new Integer("17")));
        lista.add(new Municipio(new Integer("02000"),"Araguaçu", new Integer("17")));
        lista.add(new Municipio(new Integer("02109"),"Araguaína", new Integer("17")));
        lista.add(new Municipio(new Integer("02158"),"Araguanã", new Integer("17")));
        lista.add(new Municipio(new Integer("02208"),"Araguatins", new Integer("17")));
        lista.add(new Municipio(new Integer("02307"),"Arapoema", new Integer("17")));
        lista.add(new Municipio(new Integer("02406"),"Arraias", new Integer("17")));
        lista.add(new Municipio(new Integer("02554"),"Augustinópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("02703"),"Aurora do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("02901"),"Axixá do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("03008"),"Babaçulândia", new Integer("17")));
        lista.add(new Municipio(new Integer("03057"),"Bandeirantes do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("03073"),"Barra do Ouro", new Integer("17")));
        lista.add(new Municipio(new Integer("03107"),"Barrolândia", new Integer("17")));
        lista.add(new Municipio(new Integer("03206"),"Bernardo Sayão", new Integer("17")));
        lista.add(new Municipio(new Integer("03305"),"Bom Jesus do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("03602"),"Brasilândia do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("03701"),"Brejinho de Nazaré", new Integer("17")));
        lista.add(new Municipio(new Integer("03800"),"Buriti do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("03826"),"Cachoeirinha", new Integer("17")));
        lista.add(new Municipio(new Integer("03842"),"Campos Lindos", new Integer("17")));
        lista.add(new Municipio(new Integer("03867"),"Cariri do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("03883"),"Carmolândia", new Integer("17")));
        lista.add(new Municipio(new Integer("03891"),"Carrasco Bonito", new Integer("17")));
        lista.add(new Municipio(new Integer("03909"),"Caseara", new Integer("17")));
        lista.add(new Municipio(new Integer("04105"),"Centenário", new Integer("17")));
        lista.add(new Municipio(new Integer("04600"),"Chapada de Areia", new Integer("17")));
        lista.add(new Municipio(new Integer("05102"),"Chapada da Natividade", new Integer("17")));
        lista.add(new Municipio(new Integer("05508"),"Colinas do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("05557"),"Combinado", new Integer("17")));
        lista.add(new Municipio(new Integer("05607"),"Conceição do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("06001"),"Couto Magalhães", new Integer("17")));
        lista.add(new Municipio(new Integer("06100"),"Cristalândia", new Integer("17")));
        lista.add(new Municipio(new Integer("06258"),"Crixás do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("06506"),"Darcinópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("07009"),"Dianópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("07108"),"Divinópolis do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("07207"),"Dois Irmãos do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("07306"),"Dueré", new Integer("17")));
        lista.add(new Municipio(new Integer("07405"),"Esperantina", new Integer("17")));
        lista.add(new Municipio(new Integer("07553"),"Fátima", new Integer("17")));
        lista.add(new Municipio(new Integer("07652"),"Figueirópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("07702"),"Filadélfia", new Integer("17")));
        lista.add(new Municipio(new Integer("08205"),"Formoso do Araguaia", new Integer("17")));
        lista.add(new Municipio(new Integer("08254"),"Fortaleza do Tabocão", new Integer("17")));
        lista.add(new Municipio(new Integer("08304"),"Goianorte", new Integer("17")));
        lista.add(new Municipio(new Integer("09005"),"Goiatins", new Integer("17")));
        lista.add(new Municipio(new Integer("09302"),"Guaraí", new Integer("17")));
        lista.add(new Municipio(new Integer("09500"),"Gurupi", new Integer("17")));
        lista.add(new Municipio(new Integer("09807"),"Ipueiras", new Integer("17")));
        lista.add(new Municipio(new Integer("10508"),"Itacajá", new Integer("17")));
        lista.add(new Municipio(new Integer("10706"),"Itaguatins", new Integer("17")));
        lista.add(new Municipio(new Integer("10904"),"Itapiratins", new Integer("17")));
        lista.add(new Municipio(new Integer("11100"),"Itaporã do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("11506"),"Jaú do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("11803"),"Juarina", new Integer("17")));
        lista.add(new Municipio(new Integer("11902"),"Lagoa da Confusão", new Integer("17")));
        lista.add(new Municipio(new Integer("11951"),"Lagoa do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("12009"),"Lajeado", new Integer("17")));
        lista.add(new Municipio(new Integer("12157"),"Lavandeira", new Integer("17")));
        lista.add(new Municipio(new Integer("12405"),"Lizarda", new Integer("17")));
        lista.add(new Municipio(new Integer("12454"),"Luzinópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("12504"),"Marianópolis do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("12702"),"Mateiros", new Integer("17")));
        lista.add(new Municipio(new Integer("12801"),"Maurilândia do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("13205"),"Miracema do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("13304"),"Miranorte", new Integer("17")));
        lista.add(new Municipio(new Integer("13601"),"Monte do Carmo", new Integer("17")));
        lista.add(new Municipio(new Integer("13700"),"Monte Santo do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("13809"),"Palmeiras do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("13957"),"Muricilândia", new Integer("17")));
        lista.add(new Municipio(new Integer("14203"),"Natividade", new Integer("17")));
        lista.add(new Municipio(new Integer("14302"),"Nazaré", new Integer("17")));
        lista.add(new Municipio(new Integer("14880"),"Nova Olinda", new Integer("17")));
        lista.add(new Municipio(new Integer("15002"),"Nova Rosalândia", new Integer("17")));
        lista.add(new Municipio(new Integer("15101"),"Novo Acordo", new Integer("17")));
        lista.add(new Municipio(new Integer("15150"),"Novo Alegre", new Integer("17")));
        lista.add(new Municipio(new Integer("15259"),"Novo Jardim", new Integer("17")));
        lista.add(new Municipio(new Integer("15507"),"Oliveira de Fátima", new Integer("17")));
        lista.add(new Municipio(new Integer("15705"),"Palmeirante", new Integer("17")));
        lista.add(new Municipio(new Integer("15754"),"Palmeirópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("16109"),"Paraíso do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("16208"),"Paranã", new Integer("17")));
        lista.add(new Municipio(new Integer("16307"),"Pau D'Arco", new Integer("17")));
        lista.add(new Municipio(new Integer("16505"),"Pedro Afonso", new Integer("17")));
        lista.add(new Municipio(new Integer("16604"),"Peixe", new Integer("17")));
        lista.add(new Municipio(new Integer("16653"),"Pequizeiro", new Integer("17")));
        lista.add(new Municipio(new Integer("16703"),"Colméia", new Integer("17")));
        lista.add(new Municipio(new Integer("17008"),"Pindorama do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("17206"),"Piraquê", new Integer("17")));
        lista.add(new Municipio(new Integer("17503"),"Pium", new Integer("17")));
        lista.add(new Municipio(new Integer("17800"),"Ponte Alta do Bom Jesus", new Integer("17")));
        lista.add(new Municipio(new Integer("17909"),"Ponte Alta do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("18006"),"Porto Alegre do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("18204"),"Porto Nacional", new Integer("17")));
        lista.add(new Municipio(new Integer("18303"),"Praia Norte", new Integer("17")));
        lista.add(new Municipio(new Integer("18402"),"Presidente Kennedy", new Integer("17")));
        lista.add(new Municipio(new Integer("18451"),"Pugmil", new Integer("17")));
        lista.add(new Municipio(new Integer("18501"),"Recursolândia", new Integer("17")));
        lista.add(new Municipio(new Integer("18550"),"Riachinho", new Integer("17")));
        lista.add(new Municipio(new Integer("18659"),"Rio da Conceição", new Integer("17")));
        lista.add(new Municipio(new Integer("18709"),"Rio dos Bois", new Integer("17")));
        lista.add(new Municipio(new Integer("18758"),"Rio Sono", new Integer("17")));
        lista.add(new Municipio(new Integer("18808"),"Sampaio", new Integer("17")));
        lista.add(new Municipio(new Integer("18840"),"Sandolândia", new Integer("17")));
        lista.add(new Municipio(new Integer("18865"),"Santa Fé do Araguaia", new Integer("17")));
        lista.add(new Municipio(new Integer("18881"),"Santa Maria do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("18899"),"Santa Rita do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("18907"),"Santa Rosa do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("19004"),"Santa Tereza do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20002"),"Santa Terezinha do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20101"),"São Bento do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20150"),"São Félix do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20200"),"São Miguel do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20259"),"São Salvador do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20309"),"São Sebastião do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20499"),"São Valério", new Integer("17")));
        lista.add(new Municipio(new Integer("20655"),"Silvanópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("20804"),"Sítio Novo do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20853"),"Sucupira", new Integer("17")));
        lista.add(new Municipio(new Integer("20903"),"Taguatinga", new Integer("17")));
        lista.add(new Municipio(new Integer("20937"),"Taipas do Tocantins", new Integer("17")));
        lista.add(new Municipio(new Integer("20978"),"Talismã", new Integer("17")));
        lista.add(new Municipio(new Integer("21000"),"Palmas", new Integer("17")));
        lista.add(new Municipio(new Integer("21109"),"Tocantínia", new Integer("17")));
        lista.add(new Municipio(new Integer("21208"),"Tocantinópolis", new Integer("17")));
        lista.add(new Municipio(new Integer("21257"),"Tupirama", new Integer("17")));
        lista.add(new Municipio(new Integer("21307"),"Tupiratins", new Integer("17")));
        lista.add(new Municipio(new Integer("22081"),"Wanderlândia", new Integer("17")));
        lista.add(new Municipio(new Integer("22107"),"Xambioá", new Integer("17")));
        lista.add(new Municipio(new Integer("00055"),"Açailândia", new Integer("21")));
        lista.add(new Municipio(new Integer("00105"),"Afonso Cunha", new Integer("21")));
        lista.add(new Municipio(new Integer("00154"),"Água Doce do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("00204"),"Alcântara", new Integer("21")));
        lista.add(new Municipio(new Integer("00303"),"Aldeias Altas", new Integer("21")));
        lista.add(new Municipio(new Integer("00402"),"Altamira do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("00436"),"Alto Alegre do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("00477"),"Alto Alegre do Pindaré", new Integer("21")));
        lista.add(new Municipio(new Integer("00501"),"Alto Parnaíba", new Integer("21")));
        lista.add(new Municipio(new Integer("00550"),"Amapá do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("00600"),"Amarante do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("00709"),"Anajatuba", new Integer("21")));
        lista.add(new Municipio(new Integer("00808"),"Anapurus", new Integer("21")));
        lista.add(new Municipio(new Integer("00832"),"Apicum-Açu", new Integer("21")));
        lista.add(new Municipio(new Integer("00873"),"Araguanã", new Integer("21")));
        lista.add(new Municipio(new Integer("00907"),"Araioses", new Integer("21")));
        lista.add(new Municipio(new Integer("00956"),"Arame", new Integer("21")));
        lista.add(new Municipio(new Integer("01004"),"Arari", new Integer("21")));
        lista.add(new Municipio(new Integer("01103"),"Axixá", new Integer("21")));
        lista.add(new Municipio(new Integer("01202"),"Bacabal", new Integer("21")));
        lista.add(new Municipio(new Integer("01251"),"Bacabeira", new Integer("21")));
        lista.add(new Municipio(new Integer("01301"),"Bacuri", new Integer("21")));
        lista.add(new Municipio(new Integer("01350"),"Bacurituba", new Integer("21")));
        lista.add(new Municipio(new Integer("01400"),"Balsas", new Integer("21")));
        lista.add(new Municipio(new Integer("01509"),"Barão de Grajaú", new Integer("21")));
        lista.add(new Municipio(new Integer("01608"),"Barra do Corda", new Integer("21")));
        lista.add(new Municipio(new Integer("01707"),"Barreirinhas", new Integer("21")));
        lista.add(new Municipio(new Integer("01731"),"Belágua", new Integer("21")));
        lista.add(new Municipio(new Integer("01772"),"Bela Vista do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("01806"),"Benedito Leite", new Integer("21")));
        lista.add(new Municipio(new Integer("01905"),"Bequimão", new Integer("21")));
        lista.add(new Municipio(new Integer("01939"),"Bernardo do Mearim", new Integer("21")));
        lista.add(new Municipio(new Integer("01970"),"Boa Vista do Gurupi", new Integer("21")));
        lista.add(new Municipio(new Integer("02002"),"Bom Jardim", new Integer("21")));
        lista.add(new Municipio(new Integer("02036"),"Bom Jesus das Selvas", new Integer("21")));
        lista.add(new Municipio(new Integer("02077"),"Bom Lugar", new Integer("21")));
        lista.add(new Municipio(new Integer("02101"),"Brejo", new Integer("21")));
        lista.add(new Municipio(new Integer("02150"),"Brejo de Areia", new Integer("21")));
        lista.add(new Municipio(new Integer("02200"),"Buriti", new Integer("21")));
        lista.add(new Municipio(new Integer("02309"),"Buriti Bravo", new Integer("21")));
        lista.add(new Municipio(new Integer("02325"),"Buriticupu", new Integer("21")));
        lista.add(new Municipio(new Integer("02358"),"Buritirana", new Integer("21")));
        lista.add(new Municipio(new Integer("02374"),"Cachoeira Grande", new Integer("21")));
        lista.add(new Municipio(new Integer("02408"),"Cajapió", new Integer("21")));
        lista.add(new Municipio(new Integer("02507"),"Cajari", new Integer("21")));
        lista.add(new Municipio(new Integer("02556"),"Campestre do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("02606"),"Cândido Mendes", new Integer("21")));
        lista.add(new Municipio(new Integer("02705"),"Cantanhede", new Integer("21")));
        lista.add(new Municipio(new Integer("02754"),"Capinzal do Norte", new Integer("21")));
        lista.add(new Municipio(new Integer("02804"),"Carolina", new Integer("21")));
        lista.add(new Municipio(new Integer("02903"),"Carutapera", new Integer("21")));
        lista.add(new Municipio(new Integer("03000"),"Caxias", new Integer("21")));
        lista.add(new Municipio(new Integer("03109"),"Cedral", new Integer("21")));
        lista.add(new Municipio(new Integer("03125"),"Central do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("03158"),"Centro do Guilherme", new Integer("21")));
        lista.add(new Municipio(new Integer("03174"),"Centro Novo do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("03208"),"Chapadinha", new Integer("21")));
        lista.add(new Municipio(new Integer("03257"),"Cidelândia", new Integer("21")));
        lista.add(new Municipio(new Integer("03307"),"Codó", new Integer("21")));
        lista.add(new Municipio(new Integer("03406"),"Coelho Neto", new Integer("21")));
        lista.add(new Municipio(new Integer("03505"),"Colinas", new Integer("21")));
        lista.add(new Municipio(new Integer("03554"),"Conceição do Lago-Açu", new Integer("21")));
        lista.add(new Municipio(new Integer("03604"),"Coroatá", new Integer("21")));
        lista.add(new Municipio(new Integer("03703"),"Cururupu", new Integer("21")));
        lista.add(new Municipio(new Integer("03752"),"Davinópolis", new Integer("21")));
        lista.add(new Municipio(new Integer("03802"),"Dom Pedro", new Integer("21")));
        lista.add(new Municipio(new Integer("03901"),"Duque Bacelar", new Integer("21")));
        lista.add(new Municipio(new Integer("04008"),"Esperantinópolis", new Integer("21")));
        lista.add(new Municipio(new Integer("04057"),"Estreito", new Integer("21")));
        lista.add(new Municipio(new Integer("04073"),"Feira Nova do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("04081"),"Fernando Falcão", new Integer("21")));
        lista.add(new Municipio(new Integer("04099"),"Formosa da Serra Negra", new Integer("21")));
        lista.add(new Municipio(new Integer("04107"),"Fortaleza dos Nogueiras", new Integer("21")));
        lista.add(new Municipio(new Integer("04206"),"Fortuna", new Integer("21")));
        lista.add(new Municipio(new Integer("04305"),"Godofredo Viana", new Integer("21")));
        lista.add(new Municipio(new Integer("04404"),"Gonçalves Dias", new Integer("21")));
        lista.add(new Municipio(new Integer("04503"),"Governador Archer", new Integer("21")));
        lista.add(new Municipio(new Integer("04552"),"Governador Edison Lobão", new Integer("21")));
        lista.add(new Municipio(new Integer("04602"),"Governador Eugênio Barros", new Integer("21")));
        lista.add(new Municipio(new Integer("04628"),"Governador Luiz Rocha", new Integer("21")));
        lista.add(new Municipio(new Integer("04651"),"Governador Newton Bello", new Integer("21")));
        lista.add(new Municipio(new Integer("04677"),"Governador Nunes Freire", new Integer("21")));
        lista.add(new Municipio(new Integer("04701"),"Graça Aranha", new Integer("21")));
        lista.add(new Municipio(new Integer("04800"),"Grajaú", new Integer("21")));
        lista.add(new Municipio(new Integer("04909"),"Guimarães", new Integer("21")));
        lista.add(new Municipio(new Integer("05005"),"Humberto de Campos", new Integer("21")));
        lista.add(new Municipio(new Integer("05104"),"Icatu", new Integer("21")));
        lista.add(new Municipio(new Integer("05153"),"Igarapé do Meio", new Integer("21")));
        lista.add(new Municipio(new Integer("05203"),"Igarapé Grande", new Integer("21")));
        lista.add(new Municipio(new Integer("05302"),"Imperatriz", new Integer("21")));
        lista.add(new Municipio(new Integer("05351"),"Itaipava do Grajaú", new Integer("21")));
        lista.add(new Municipio(new Integer("05401"),"Itapecuru Mirim", new Integer("21")));
        lista.add(new Municipio(new Integer("05427"),"Itinga do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("05450"),"Jatobá", new Integer("21")));
        lista.add(new Municipio(new Integer("05476"),"Jenipapo dos Vieiras", new Integer("21")));
        lista.add(new Municipio(new Integer("05500"),"João Lisboa", new Integer("21")));
        lista.add(new Municipio(new Integer("05609"),"Joselândia", new Integer("21")));
        lista.add(new Municipio(new Integer("05658"),"Junco do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("05708"),"Lago da Pedra", new Integer("21")));
        lista.add(new Municipio(new Integer("05807"),"Lago do Junco", new Integer("21")));
        lista.add(new Municipio(new Integer("05906"),"Lago Verde", new Integer("21")));
        lista.add(new Municipio(new Integer("05922"),"Lagoa do Mato", new Integer("21")));
        lista.add(new Municipio(new Integer("05948"),"Lago dos Rodrigues", new Integer("21")));
        lista.add(new Municipio(new Integer("05963"),"Lagoa Grande do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("05989"),"Lajeado Novo", new Integer("21")));
        lista.add(new Municipio(new Integer("06003"),"Lima Campos", new Integer("21")));
        lista.add(new Municipio(new Integer("06102"),"Loreto", new Integer("21")));
        lista.add(new Municipio(new Integer("06201"),"Luís Domingues", new Integer("21")));
        lista.add(new Municipio(new Integer("06300"),"Magalhães de Almeida", new Integer("21")));
        lista.add(new Municipio(new Integer("06326"),"Maracaçumé", new Integer("21")));
        lista.add(new Municipio(new Integer("06359"),"Marajá do Sena", new Integer("21")));
        lista.add(new Municipio(new Integer("06375"),"Maranhãozinho", new Integer("21")));
        lista.add(new Municipio(new Integer("06409"),"Mata Roma", new Integer("21")));
        lista.add(new Municipio(new Integer("06508"),"Matinha", new Integer("21")));
        lista.add(new Municipio(new Integer("06607"),"Matões", new Integer("21")));
        lista.add(new Municipio(new Integer("06631"),"Matões do Norte", new Integer("21")));
        lista.add(new Municipio(new Integer("06672"),"Milagres do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("06706"),"Mirador", new Integer("21")));
        lista.add(new Municipio(new Integer("06755"),"Miranda do Norte", new Integer("21")));
        lista.add(new Municipio(new Integer("06805"),"Mirinzal", new Integer("21")));
        lista.add(new Municipio(new Integer("06904"),"Monção", new Integer("21")));
        lista.add(new Municipio(new Integer("07001"),"Montes Altos", new Integer("21")));
        lista.add(new Municipio(new Integer("07100"),"Morros", new Integer("21")));
        lista.add(new Municipio(new Integer("07209"),"Nina Rodrigues", new Integer("21")));
        lista.add(new Municipio(new Integer("07258"),"Nova Colinas", new Integer("21")));
        lista.add(new Municipio(new Integer("07308"),"Nova Iorque", new Integer("21")));
        lista.add(new Municipio(new Integer("07357"),"Nova Olinda do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("07407"),"Olho d'Água das Cunhãs", new Integer("21")));
        lista.add(new Municipio(new Integer("07456"),"Olinda Nova do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("07506"),"Paço do Lumiar", new Integer("21")));
        lista.add(new Municipio(new Integer("07605"),"Palmeirândia", new Integer("21")));
        lista.add(new Municipio(new Integer("07704"),"Paraibano", new Integer("21")));
        lista.add(new Municipio(new Integer("07803"),"Parnarama", new Integer("21")));
        lista.add(new Municipio(new Integer("07902"),"Passagem Franca", new Integer("21")));
        lista.add(new Municipio(new Integer("08009"),"Pastos Bons", new Integer("21")));
        lista.add(new Municipio(new Integer("08058"),"Paulino Neves", new Integer("21")));
        lista.add(new Municipio(new Integer("08108"),"Paulo Ramos", new Integer("21")));
        lista.add(new Municipio(new Integer("08207"),"Pedreiras", new Integer("21")));
        lista.add(new Municipio(new Integer("08256"),"Pedro do Rosário", new Integer("21")));
        lista.add(new Municipio(new Integer("08306"),"Penalva", new Integer("21")));
        lista.add(new Municipio(new Integer("08405"),"Peri Mirim", new Integer("21")));
        lista.add(new Municipio(new Integer("08454"),"Peritoró", new Integer("21")));
        lista.add(new Municipio(new Integer("08504"),"Pindaré-Mirim", new Integer("21")));
        lista.add(new Municipio(new Integer("08603"),"Pinheiro", new Integer("21")));
        lista.add(new Municipio(new Integer("08702"),"Pio XII", new Integer("21")));
        lista.add(new Municipio(new Integer("08801"),"Pirapemas", new Integer("21")));
        lista.add(new Municipio(new Integer("08900"),"Poção de Pedras", new Integer("21")));
        lista.add(new Municipio(new Integer("09007"),"Porto Franco", new Integer("21")));
        lista.add(new Municipio(new Integer("09056"),"Porto Rico do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("09106"),"Presidente Dutra", new Integer("21")));
        lista.add(new Municipio(new Integer("09205"),"Presidente Juscelino", new Integer("21")));
        lista.add(new Municipio(new Integer("09239"),"Presidente Médici", new Integer("21")));
        lista.add(new Municipio(new Integer("09270"),"Presidente Sarney", new Integer("21")));
        lista.add(new Municipio(new Integer("09304"),"Presidente Vargas", new Integer("21")));
        lista.add(new Municipio(new Integer("09403"),"Primeira Cruz", new Integer("21")));
        lista.add(new Municipio(new Integer("09452"),"Raposa", new Integer("21")));
        lista.add(new Municipio(new Integer("09502"),"Riachão", new Integer("21")));
        lista.add(new Municipio(new Integer("09551"),"Ribamar Fiquene", new Integer("21")));
        lista.add(new Municipio(new Integer("09601"),"Rosário", new Integer("21")));
        lista.add(new Municipio(new Integer("09700"),"Sambaíba", new Integer("21")));
        lista.add(new Municipio(new Integer("09759"),"Santa Filomena do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("09809"),"Santa Helena", new Integer("21")));
        lista.add(new Municipio(new Integer("09908"),"Santa Inês", new Integer("21")));
        lista.add(new Municipio(new Integer("10005"),"Santa Luzia", new Integer("21")));
        lista.add(new Municipio(new Integer("10039"),"Santa Luzia do Paruá", new Integer("21")));
        lista.add(new Municipio(new Integer("10104"),"Santa Quitéria do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("10203"),"Santa Rita", new Integer("21")));
        lista.add(new Municipio(new Integer("10237"),"Santana do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("10278"),"Santo Amaro do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("10302"),"Santo Antônio dos Lopes", new Integer("21")));
        lista.add(new Municipio(new Integer("10401"),"São Benedito do Rio Preto", new Integer("21")));
        lista.add(new Municipio(new Integer("10500"),"São Bento", new Integer("21")));
        lista.add(new Municipio(new Integer("10609"),"São Bernardo", new Integer("21")));
        lista.add(new Municipio(new Integer("10658"),"São Domingos do Azeitão", new Integer("21")));
        lista.add(new Municipio(new Integer("10708"),"São Domingos do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("10807"),"São Félix de Balsas", new Integer("21")));
        lista.add(new Municipio(new Integer("10856"),"São Francisco do Brejão", new Integer("21")));
        lista.add(new Municipio(new Integer("10906"),"São Francisco do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("11003"),"São João Batista", new Integer("21")));
        lista.add(new Municipio(new Integer("11029"),"São João do Carú", new Integer("21")));
        lista.add(new Municipio(new Integer("11052"),"São João do Paraíso", new Integer("21")));
        lista.add(new Municipio(new Integer("11078"),"São João do Soter", new Integer("21")));
        lista.add(new Municipio(new Integer("11102"),"São João dos Patos", new Integer("21")));
        lista.add(new Municipio(new Integer("11201"),"São José de Ribamar", new Integer("21")));
        lista.add(new Municipio(new Integer("11250"),"São José dos Basílios", new Integer("21")));
        lista.add(new Municipio(new Integer("11300"),"São Luís", new Integer("21")));
        lista.add(new Municipio(new Integer("11409"),"São Luís Gonzaga do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("11508"),"São Mateus do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("11532"),"São Pedro da Água Branca", new Integer("21")));
        lista.add(new Municipio(new Integer("11573"),"São Pedro dos Crentes", new Integer("21")));
        lista.add(new Municipio(new Integer("11607"),"São Raimundo das Mangabeiras", new Integer("21")));
        lista.add(new Municipio(new Integer("11631"),"São Raimundo do Doca Bezerra", new Integer("21")));
        lista.add(new Municipio(new Integer("11672"),"São Roberto", new Integer("21")));
        lista.add(new Municipio(new Integer("11706"),"São Vicente Ferrer", new Integer("21")));
        lista.add(new Municipio(new Integer("11722"),"Satubinha", new Integer("21")));
        lista.add(new Municipio(new Integer("11748"),"Senador Alexandre Costa", new Integer("21")));
        lista.add(new Municipio(new Integer("11763"),"Senador La Rocque", new Integer("21")));
        lista.add(new Municipio(new Integer("11789"),"Serrano do Maranhão", new Integer("21")));
        lista.add(new Municipio(new Integer("11805"),"Sítio Novo", new Integer("21")));
        lista.add(new Municipio(new Integer("11904"),"Sucupira do Norte", new Integer("21")));
        lista.add(new Municipio(new Integer("11953"),"Sucupira do Riachão", new Integer("21")));
        lista.add(new Municipio(new Integer("12001"),"Tasso Fragoso", new Integer("21")));
        lista.add(new Municipio(new Integer("12100"),"Timbiras", new Integer("21")));
        lista.add(new Municipio(new Integer("12209"),"Timon", new Integer("21")));
        lista.add(new Municipio(new Integer("12233"),"Trizidela do Vale", new Integer("21")));
        lista.add(new Municipio(new Integer("12274"),"Tufilândia", new Integer("21")));
        lista.add(new Municipio(new Integer("12308"),"Tuntum", new Integer("21")));
        lista.add(new Municipio(new Integer("12407"),"Turiaçu", new Integer("21")));
        lista.add(new Municipio(new Integer("12456"),"Turilândia", new Integer("21")));
        lista.add(new Municipio(new Integer("12506"),"Tutóia", new Integer("21")));
        lista.add(new Municipio(new Integer("12605"),"Urbano Santos", new Integer("21")));
        lista.add(new Municipio(new Integer("12704"),"Vargem Grande", new Integer("21")));
        lista.add(new Municipio(new Integer("12803"),"Viana", new Integer("21")));
        lista.add(new Municipio(new Integer("12852"),"Vila Nova dos Martírios", new Integer("21")));
        lista.add(new Municipio(new Integer("12902"),"Vitória do Mearim", new Integer("21")));
        lista.add(new Municipio(new Integer("13009"),"Vitorino Freire", new Integer("21")));
        lista.add(new Municipio(new Integer("14007"),"Zé Doca", new Integer("21")));
        lista.add(new Municipio(new Integer("00053"),"Acauã", new Integer("22")));
        lista.add(new Municipio(new Integer("00103"),"Agricolândia", new Integer("22")));
        lista.add(new Municipio(new Integer("00202"),"Água Branca", new Integer("22")));
        lista.add(new Municipio(new Integer("00251"),"Alagoinha do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("00277"),"Alegrete do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("00301"),"Alto Longá", new Integer("22")));
        lista.add(new Municipio(new Integer("00400"),"Altos", new Integer("22")));
        lista.add(new Municipio(new Integer("00459"),"Alvorada do Gurguéia", new Integer("22")));
        lista.add(new Municipio(new Integer("00509"),"Amarante", new Integer("22")));
        lista.add(new Municipio(new Integer("00608"),"Angical do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("00707"),"Anísio de Abreu", new Integer("22")));
        lista.add(new Municipio(new Integer("00806"),"Antônio Almeida", new Integer("22")));
        lista.add(new Municipio(new Integer("00905"),"Aroazes", new Integer("22")));
        lista.add(new Municipio(new Integer("00954"),"Aroeiras do Itaim", new Integer("22")));
        lista.add(new Municipio(new Integer("01002"),"Arraial", new Integer("22")));
        lista.add(new Municipio(new Integer("01051"),"Assunção do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01101"),"Avelino Lopes", new Integer("22")));
        lista.add(new Municipio(new Integer("01150"),"Baixa Grande do Ribeiro", new Integer("22")));
        lista.add(new Municipio(new Integer("01176"),"Barra D'Alcântara", new Integer("22")));
        lista.add(new Municipio(new Integer("01200"),"Barras", new Integer("22")));
        lista.add(new Municipio(new Integer("01309"),"Barreiras do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01408"),"Barro Duro", new Integer("22")));
        lista.add(new Municipio(new Integer("01507"),"Batalha", new Integer("22")));
        lista.add(new Municipio(new Integer("01556"),"Bela Vista do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01572"),"Belém do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01606"),"Beneditinos", new Integer("22")));
        lista.add(new Municipio(new Integer("01705"),"Bertolínia", new Integer("22")));
        lista.add(new Municipio(new Integer("01739"),"Betânia do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01770"),"Boa Hora", new Integer("22")));
        lista.add(new Municipio(new Integer("01804"),"Bocaina", new Integer("22")));
        lista.add(new Municipio(new Integer("01903"),"Bom Jesus", new Integer("22")));
        lista.add(new Municipio(new Integer("01919"),"Bom Princípio do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01929"),"Bonfim do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01945"),"Boqueirão do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("01960"),"Brasileira", new Integer("22")));
        lista.add(new Municipio(new Integer("01988"),"Brejo do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02000"),"Buriti dos Lopes", new Integer("22")));
        lista.add(new Municipio(new Integer("02026"),"Buriti dos Montes", new Integer("22")));
        lista.add(new Municipio(new Integer("02059"),"Cabeceiras do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02075"),"Cajazeiras do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02083"),"Cajueiro da Praia", new Integer("22")));
        lista.add(new Municipio(new Integer("02091"),"Caldeirão Grande do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02109"),"Campinas do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02117"),"Campo Alegre do Fidalgo", new Integer("22")));
        lista.add(new Municipio(new Integer("02133"),"Campo Grande do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02174"),"Campo Largo do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02208"),"Campo Maior", new Integer("22")));
        lista.add(new Municipio(new Integer("02251"),"Canavieira", new Integer("22")));
        lista.add(new Municipio(new Integer("02307"),"Canto do Buriti", new Integer("22")));
        lista.add(new Municipio(new Integer("02406"),"Capitão de Campos", new Integer("22")));
        lista.add(new Municipio(new Integer("02455"),"Capitão Gervásio Oliveira", new Integer("22")));
        lista.add(new Municipio(new Integer("02505"),"Caracol", new Integer("22")));
        lista.add(new Municipio(new Integer("02539"),"Caraúbas do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02554"),"Caridade do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02604"),"Castelo do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02653"),"Caxingó", new Integer("22")));
        lista.add(new Municipio(new Integer("02703"),"Cocal", new Integer("22")));
        lista.add(new Municipio(new Integer("02711"),"Cocal de Telha", new Integer("22")));
        lista.add(new Municipio(new Integer("02729"),"Cocal dos Alves", new Integer("22")));
        lista.add(new Municipio(new Integer("02737"),"Coivaras", new Integer("22")));
        lista.add(new Municipio(new Integer("02752"),"Colônia do Gurguéia", new Integer("22")));
        lista.add(new Municipio(new Integer("02778"),"Colônia do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("02802"),"Conceição do Canindé", new Integer("22")));
        lista.add(new Municipio(new Integer("02851"),"Coronel José Dias", new Integer("22")));
        lista.add(new Municipio(new Integer("02901"),"Corrente", new Integer("22")));
        lista.add(new Municipio(new Integer("03008"),"Cristalândia do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("03107"),"Cristino Castro", new Integer("22")));
        lista.add(new Municipio(new Integer("03206"),"Curimatá", new Integer("22")));
        lista.add(new Municipio(new Integer("03230"),"Currais", new Integer("22")));
        lista.add(new Municipio(new Integer("03255"),"Curralinhos", new Integer("22")));
        lista.add(new Municipio(new Integer("03271"),"Curral Novo do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("03305"),"Demerval Lobão", new Integer("22")));
        lista.add(new Municipio(new Integer("03354"),"Dirceu Arcoverde", new Integer("22")));
        lista.add(new Municipio(new Integer("03404"),"Dom Expedito Lopes", new Integer("22")));
        lista.add(new Municipio(new Integer("03420"),"Domingos Mourão", new Integer("22")));
        lista.add(new Municipio(new Integer("03453"),"Dom Inocêncio", new Integer("22")));
        lista.add(new Municipio(new Integer("03503"),"Elesbão Veloso", new Integer("22")));
        lista.add(new Municipio(new Integer("03602"),"Eliseu Martins", new Integer("22")));
        lista.add(new Municipio(new Integer("03701"),"Esperantina", new Integer("22")));
        lista.add(new Municipio(new Integer("03750"),"Fartura do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("03800"),"Flores do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("03859"),"Floresta do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("03909"),"Floriano", new Integer("22")));
        lista.add(new Municipio(new Integer("04006"),"Francinópolis", new Integer("22")));
        lista.add(new Municipio(new Integer("04105"),"Francisco Ayres", new Integer("22")));
        lista.add(new Municipio(new Integer("04154"),"Francisco Macedo", new Integer("22")));
        lista.add(new Municipio(new Integer("04204"),"Francisco Santos", new Integer("22")));
        lista.add(new Municipio(new Integer("04303"),"Fronteiras", new Integer("22")));
        lista.add(new Municipio(new Integer("04352"),"Geminiano", new Integer("22")));
        lista.add(new Municipio(new Integer("04402"),"Gilbués", new Integer("22")));
        lista.add(new Municipio(new Integer("04501"),"Guadalupe", new Integer("22")));
        lista.add(new Municipio(new Integer("04550"),"Guaribas", new Integer("22")));
        lista.add(new Municipio(new Integer("04600"),"Hugo Napoleão", new Integer("22")));
        lista.add(new Municipio(new Integer("04659"),"Ilha Grande", new Integer("22")));
        lista.add(new Municipio(new Integer("04709"),"Inhuma", new Integer("22")));
        lista.add(new Municipio(new Integer("04808"),"Ipiranga do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("04907"),"Isaías Coelho", new Integer("22")));
        lista.add(new Municipio(new Integer("05003"),"Itainópolis", new Integer("22")));
        lista.add(new Municipio(new Integer("05102"),"Itaueira", new Integer("22")));
        lista.add(new Municipio(new Integer("05151"),"Jacobina do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("05201"),"Jaicós", new Integer("22")));
        lista.add(new Municipio(new Integer("05250"),"Jardim do Mulato", new Integer("22")));
        lista.add(new Municipio(new Integer("05276"),"Jatobá do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("05300"),"Jerumenha", new Integer("22")));
        lista.add(new Municipio(new Integer("05359"),"João Costa", new Integer("22")));
        lista.add(new Municipio(new Integer("05409"),"Joaquim Pires", new Integer("22")));
        lista.add(new Municipio(new Integer("05458"),"Joca Marques", new Integer("22")));
        lista.add(new Municipio(new Integer("05508"),"José de Freitas", new Integer("22")));
        lista.add(new Municipio(new Integer("05516"),"Juazeiro do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("05524"),"Júlio Borges", new Integer("22")));
        lista.add(new Municipio(new Integer("05532"),"Jurema", new Integer("22")));
        lista.add(new Municipio(new Integer("05540"),"Lagoinha do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("05557"),"Lagoa Alegre", new Integer("22")));
        lista.add(new Municipio(new Integer("05565"),"Lagoa do Barro do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("05573"),"Lagoa de São Francisco", new Integer("22")));
        lista.add(new Municipio(new Integer("05581"),"Lagoa do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("05599"),"Lagoa do Sítio", new Integer("22")));
        lista.add(new Municipio(new Integer("05607"),"Landri Sales", new Integer("22")));
        lista.add(new Municipio(new Integer("05706"),"Luís Correia", new Integer("22")));
        lista.add(new Municipio(new Integer("05805"),"Luzilândia", new Integer("22")));
        lista.add(new Municipio(new Integer("05854"),"Madeiro", new Integer("22")));
        lista.add(new Municipio(new Integer("05904"),"Manoel Emídio", new Integer("22")));
        lista.add(new Municipio(new Integer("05953"),"Marcolândia", new Integer("22")));
        lista.add(new Municipio(new Integer("06001"),"Marcos Parente", new Integer("22")));
        lista.add(new Municipio(new Integer("06050"),"Massapê do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("06100"),"Matias Olímpio", new Integer("22")));
        lista.add(new Municipio(new Integer("06209"),"Miguel Alves", new Integer("22")));
        lista.add(new Municipio(new Integer("06308"),"Miguel Leão", new Integer("22")));
        lista.add(new Municipio(new Integer("06357"),"Milton Brandão", new Integer("22")));
        lista.add(new Municipio(new Integer("06407"),"Monsenhor Gil", new Integer("22")));
        lista.add(new Municipio(new Integer("06506"),"Monsenhor Hipólito", new Integer("22")));
        lista.add(new Municipio(new Integer("06605"),"Monte Alegre do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("06654"),"Morro Cabeça no Tempo", new Integer("22")));
        lista.add(new Municipio(new Integer("06670"),"Morro do Chapéu do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("06696"),"Murici dos Portelas", new Integer("22")));
        lista.add(new Municipio(new Integer("06704"),"Nazaré do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("06720"),"Nazária", new Integer("22")));
        lista.add(new Municipio(new Integer("06753"),"Nossa Senhora de Nazaré", new Integer("22")));
        lista.add(new Municipio(new Integer("06803"),"Nossa Senhora dos Remédios", new Integer("22")));
        lista.add(new Municipio(new Integer("06902"),"Novo Oriente do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("06951"),"Novo Santo Antônio", new Integer("22")));
        lista.add(new Municipio(new Integer("07009"),"Oeiras", new Integer("22")));
        lista.add(new Municipio(new Integer("07108"),"Olho D'Água do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("07207"),"Padre Marcos", new Integer("22")));
        lista.add(new Municipio(new Integer("07306"),"Paes Landim", new Integer("22")));
        lista.add(new Municipio(new Integer("07355"),"Pajeú do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("07405"),"Palmeira do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("07504"),"Palmeirais", new Integer("22")));
        lista.add(new Municipio(new Integer("07553"),"Paquetá", new Integer("22")));
        lista.add(new Municipio(new Integer("07603"),"Parnaguá", new Integer("22")));
        lista.add(new Municipio(new Integer("07702"),"Parnaíba", new Integer("22")));
        lista.add(new Municipio(new Integer("07751"),"Passagem Franca do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("07777"),"Patos do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("07793"),"Pau D'Arco do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("07801"),"Paulistana", new Integer("22")));
        lista.add(new Municipio(new Integer("07850"),"Pavussu", new Integer("22")));
        lista.add(new Municipio(new Integer("07900"),"Pedro II", new Integer("22")));
        lista.add(new Municipio(new Integer("07934"),"Pedro Laurentino", new Integer("22")));
        lista.add(new Municipio(new Integer("07959"),"Nova Santa Rita", new Integer("22")));
        lista.add(new Municipio(new Integer("08007"),"Picos", new Integer("22")));
        lista.add(new Municipio(new Integer("08106"),"Pimenteiras", new Integer("22")));
        lista.add(new Municipio(new Integer("08205"),"Pio IX", new Integer("22")));
        lista.add(new Municipio(new Integer("08304"),"Piracuruca", new Integer("22")));
        lista.add(new Municipio(new Integer("08403"),"Piripiri", new Integer("22")));
        lista.add(new Municipio(new Integer("08502"),"Porto", new Integer("22")));
        lista.add(new Municipio(new Integer("08551"),"Porto Alegre do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("08601"),"Prata do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("08650"),"Queimada Nova", new Integer("22")));
        lista.add(new Municipio(new Integer("08700"),"Redenção do Gurguéia", new Integer("22")));
        lista.add(new Municipio(new Integer("08809"),"Regeneração", new Integer("22")));
        lista.add(new Municipio(new Integer("08858"),"Riacho Frio", new Integer("22")));
        lista.add(new Municipio(new Integer("08874"),"Ribeira do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("08908"),"Ribeiro Gonçalves", new Integer("22")));
        lista.add(new Municipio(new Integer("09005"),"Rio Grande do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09104"),"Santa Cruz do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09153"),"Santa Cruz dos Milagres", new Integer("22")));
        lista.add(new Municipio(new Integer("09203"),"Santa Filomena", new Integer("22")));
        lista.add(new Municipio(new Integer("09302"),"Santa Luz", new Integer("22")));
        lista.add(new Municipio(new Integer("09351"),"Santana do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09377"),"Santa Rosa do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09401"),"Santo Antônio de Lisboa", new Integer("22")));
        lista.add(new Municipio(new Integer("09450"),"Santo Antônio dos Milagres", new Integer("22")));
        lista.add(new Municipio(new Integer("09500"),"Santo Inácio do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09559"),"São Braz do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09609"),"São Félix do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09658"),"São Francisco de Assis do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09708"),"São Francisco do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09757"),"São Gonçalo do Gurguéia", new Integer("22")));
        lista.add(new Municipio(new Integer("09807"),"São Gonçalo do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("09856"),"São João da Canabrava", new Integer("22")));
        lista.add(new Municipio(new Integer("09872"),"São João da Fronteira", new Integer("22")));
        lista.add(new Municipio(new Integer("09906"),"São João da Serra", new Integer("22")));
        lista.add(new Municipio(new Integer("09955"),"São João da Varjota", new Integer("22")));
        lista.add(new Municipio(new Integer("09971"),"São João do Arraial", new Integer("22")));
        lista.add(new Municipio(new Integer("10003"),"São João do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("10052"),"São José do Divino", new Integer("22")));
        lista.add(new Municipio(new Integer("10102"),"São José do Peixe", new Integer("22")));
        lista.add(new Municipio(new Integer("10201"),"São José do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("10300"),"São Julião", new Integer("22")));
        lista.add(new Municipio(new Integer("10359"),"São Lourenço do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("10375"),"São Luis do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("10383"),"São Miguel da Baixa Grande", new Integer("22")));
        lista.add(new Municipio(new Integer("10391"),"São Miguel do Fidalgo", new Integer("22")));
        lista.add(new Municipio(new Integer("10409"),"São Miguel do Tapuio", new Integer("22")));
        lista.add(new Municipio(new Integer("10508"),"São Pedro do Piauí", new Integer("22")));
        lista.add(new Municipio(new Integer("10607"),"São Raimundo Nonato", new Integer("22")));

        Collections.sort(lista);
        return lista;
    }

    public List<Municipio> listarPorEstado(Integer codigoEstado) {
        List<Municipio> lista = new ArrayList<Municipio>();
        for (Municipio municipio : listar()) {
            if (municipio.getCodigoEstado().equals(codigoEstado) == true) {
                lista.add(municipio);
            }
        }
        return lista;
    }
}
